### ISSUE TITLE
_ServiceBrowserBase._async_send_ready_queries_schedule_next() blocking?

### ISSUE THREAD

**Issue by dominikkarall** [jstasiak/python-zeroconf#1005]
From time to time I get the following message with asyncio debug on:
```
2021-10-07 21:05:22,047 - WARNING  - asyncio: Executing <TimerHandle when=1265.868092168 _ServiceBrowserBase._async_send_ready_queries_schedule_next() created at /home/dominikkarall/.local/lib/python3.7/site-packages/zeroconf/_services/browser.py:488> took 0.247 seconds
2021-10-07 21:05:22,262 - WARNING  - asyncio: Executing <TimerHandle when=1266.114710128 _ServiceBrowserBase._async_send_ready_queries_schedule_next() created at /home/dominikkarall/.local/lib/python3.7/site-packages/zeroconf/_services/browser.py:488> took 0.137 seconds
```

Could it be that there is some blocking code within that function?

**Comment by bdraco** [comment]
I don't see any code that could block.

Is it possible its just computationally expensive if you have a lot of registered types?

**Comment by jstasiak** [comment]
I'd consider a long loop to be blocking code in this context (if this is what's actually happening) – maybe it'd make sense to use the `asyncio.sleep(0)` trick to divide long computation into chunks

**Comment by bdraco** [comment]
> I'd consider a long loop to be blocking code in this context (if this is what's actually happening) – maybe it'd make sense to use the `asyncio.sleep(0)` trick to divide long computation into chunks

That's a good idea if that's what's happening 👍

I did some testing with this and I couldn't get it to be anywhere near that slow even on my busiest network. 

I think we need more information about the use case to figure out how to proceed

**Comment by dominikkarall** [comment]
It's a service browser which runs all the time and scans for _http._tcp.local.
https://github.com/dominikkarall/fhempy/blob/master/FHEM/bindings/python/fhempy/lib/core/discover_fhempy/discover_fhempy.py

**Comment by dominikkarall** [comment]
Actually just 10 devices. I'm running it on a RPi 4 with Python 3.9.

**Comment by bdraco** [comment]
I've been over it quite a few times.  We can probably squeeze out a bit more performance in the packet construction, but with 10 hosts it should still be quite fast. Even with the 60~ `_hap_._tcp.local.` devices I have on my network with asyncio debug on, I never get a warning there or it showing up in a cProfile.

Can you turn on debug logging and paste one of the packets that gets generated from that function?

**Comment by bdraco** [comment]
> Can you please let me know the name of the logger which one I should set to DEBUG? Thx!

`zeroconf`

**Comment by dominikkarall** [comment]
```
2021-10-10 13:29:35,851 - WARNING  - asyncio: Executing <TimerHandle when=144956.947732479 _ServiceBrowserBase._async_send_ready_queries_schedule_next() created at /home/dominikkarall/.local/lib/python3.9/site-packages/zeroconf/_services/browser.py:486> took 0.241 seconds
2021-10-10 13:29:36,649 - WARNING  - asyncio: Executing <TimerHandle when=144957.847381034 _ServiceBrowserBase._async_send_ready_queries_schedule_next() created at /home/dominikkarall/.local/lib/python3.9/site-packages/zeroconf/_services/browser.py:486> took 0.138 seconds
```

zeroconf.cprof
https://drive.google.com/file/d/1-uS6_Yb-VQuMDBd9-JA8lkzlvxDtBv3A/view?usp=sharing

**Comment by bdraco** [comment]
We have a guard to protect against excessive refreshes from records with very small TTLs, but it looks like there might be another case of that
https://github.com/jstasiak/python-zeroconf/blob/master/zeroconf/_handlers.py#L129


How are the records being registered?

**Comment by bdraco** [comment]
I can see two ways for this to happen.  

1. Zeroconf somehow gets shutdown without the service browser being canceled

Can you try this patch?

```
diff --git a/zeroconf/_services/browser.py b/zeroconf/_services/browser.py
index f6448fd..dd5bf4f 100644
--- a/zeroconf/_services/browser.py
+++ b/zeroconf/_services/browser.py
@@ -465,9 +465,6 @@ class _ServiceBrowserBase(RecordUpdateListener):
 
     def _async_send_ready_queries(self) -> None:
         """Send any ready queries."""
-        if self.done or self.zc.done:
-            return
-
         outs = self._generate_ready_queries(self._first_request)
         if outs:
             self._first_request = False
@@ -476,6 +473,8 @@ class _ServiceBrowserBase(RecordUpdateListener):
 
     def _async_send_ready_queries_schedule_next(self) -> None:
         """Send ready queries and schedule next one."""
+        if self.done or self.zc.done:
+            return
         self._async_send_ready_queries()
         self._async_schedule_next()
 
```


2. The ServiceBrowser instantiated with a delay of 0 so it constantly refreshes the records

**Comment by dominikkarall** [comment]
The patch works 👍  I checked 2 times with and without the patch.

**Comment by bdraco** [comment]
I pushed this change to a few production machines. Once the full 4500s window passes (about ~2100 left), I'll feel confident about this change and I'll put together the release bump.
