### ISSUE TITLE
0.18.0 tests fail when running against python3 (3.6)

### ISSUE THREAD

**Issue by nullr0ute** [jstasiak/python-zeroconf#101]
When running the tests (in Fedora 26) for python 3 against python 3.6 I get a test failure saying "ModuleNotFoundError: No module named 'mock'" when the mock plugin is reported at the the beginning of the test and the same test works against python2.

Output:

<pre>
+ cd python-zeroconf-0.18.0
+ /usr/bin/python2 -m pytest -k 'not integration'
============================= test session starts ==============================
platform linux2 -- Python 2.7.13, pytest-3.0.6, py-1.4.32, pluggy-0.4.0
rootdir: /builddir/build/BUILD/python-zeroconf-0.18.0, inifile: 
plugins: mock-1.2
collected 39 items
test_zeroconf.py ...................................
============================== 4 tests deselected ==============================
=================== 35 passed, 4 deselected in 12.63 seconds ===================
+ /usr/bin/python3 -m pytest -k 'not integration'
============================= test session starts ==============================
platform linux -- Python 3.6.0, pytest-3.0.6, py-1.4.32, pluggy-0.4.0
rootdir: /builddir/build/BUILD/python-zeroconf-0.18.0, inifile: 
plugins: mock-1.2
collected 39 items
test_zeroconf.py .......................F...........
=================================== FAILURES ===================================
___________________________ Names.test_lots_of_names ___________________________
self = <test_zeroconf.Names testMethod=test_lots_of_names>
    def test_lots_of_names(self):
    
        # instantiate a zeroconf instance
        zc = Zeroconf(interfaces=['127.0.0.1'])
    
        # create a bunch of servers
        type_ = "_my-service._tcp.local."
        name = 'a wonderful service'
        server_count = 300
        self.generate_many_hosts(zc, type_, name, server_count)
    
        # verify that name changing works
        self.verify_name_change(zc, type_, name, server_count)
    
        # we are going to monkey patch the zeroconf send to check packet sizes
        old_send = zc.send
    
        # needs to be a list so that we can modify it in our phony send
        longest_packet = [0, None]
    
        def send(out, addr=r._MDNS_ADDR, port=r._MDNS_PORT):
            """Sends an outgoing packet."""
            packet = out.packet()
            if longest_packet[0] < len(packet):
                longest_packet[0] = len(packet)
                longest_packet[1] = out
            old_send(out, addr=addr, port=port)
    
        # monkey patch the zeroconf send
        zc.send = send
    
        # dummy service callback
        def on_service_state_change(zeroconf, service_type, state_change, name):
            pass
    
        # start a browser
        browser = ServiceBrowser(zc, type_, [on_service_state_change])
    
        # wait until the browse request packet has maxed out in size
        sleep_count = 0
        while sleep_count < 100 and \
                longest_packet[0] < r._MAX_MSG_ABSOLUTE - 100:
            sleep_count += 1
            time.sleep(0.1)
    
        browser.cancel()
        time.sleep(0.5)
    
        import zeroconf
        zeroconf.log.debug('sleep_count %d, sized %d',
                           sleep_count, longest_packet[0])
    
        # now the browser has sent at least one request, verify the size
        assert longest_packet[0] <= r._MAX_MSG_ABSOLUTE
        assert longest_packet[0] >= r._MAX_MSG_ABSOLUTE - 100
    
        # mock zeroconf's logger warning() and debug()
>       from mock import patch
E       ModuleNotFoundError: No module named 'mock'
test_zeroconf.py:275: ModuleNotFoundError
============================== 4 tests deselected ==============================
============== 1 failed, 34 passed, 4 deselected in 17.47 seconds ==============
</pre>

**Comment by jstasiak** [comment]
The test dependencies are declared in the ``requirements-dev.txt`` file and ``mock`` is there (not an ideal situation but the CI builds use it and it should be transparent what's going on).

Also note that pytest is not  used by the project so it may not work correctly with the codebase. I'll close this issue as tests run on Python 3 correctly.
