### ISSUE TITLE
Service name regex

### ISSUE THREAD

**Issue by CharlesBlonde** [jstasiak/python-zeroconf#102]
Hi,

I'm currently working on writing a library in order to control Dyson Pure Cool link devices (http://www.dyson.com/air-treatment/purifiers/dyson-pure-hot-cool-link.aspx) and I have an issue with the service name.
The service name is *dyson_mqtt* and the validation regex (https://github.com/jstasiak/python-zeroconf/blob/master/zeroconf.py#L151) doesn't accept this name because of the underscore.

Of course, it's quite simple to provide a pull request to update this regex but I think this regex exists to follow the RFC. Can you confirm an underscore in the service name is not valid ?

If yes, what can be the best solution ? Right now I'm using an hacked version with the following regex:

```python
_HAS_ONLY_A_TO_Z_NUM_HYPHEN = re.compile(r'^[A-Za-z0-9\-\_]+$')
```

But I would prefer to use an official version. If I have no choice I'll embedded this hacked version but I would like to avoid

Thanks for your help,

Charles

**Comment by stephenrauch** [comment]
The RFC is here: https://tools.ietf.org/html/rfc6335#section-5.1

Having said that... the change to validate to the RFC has proven problematic, since as you have found, it is violated by devices that people need to talk to.  It should likely be changed to a warning of some sort.  And then only on a service create not for when browsing.  I made the original change but have otherwise occupied for the last couple of months, to revise it to something more accommodating.

**Comment by tadly** [comment]
I'll just go ahead and be that annoying **bump** guy :)

Nvidia with their gamestream stuff also publishes an invalid type `_nvstream_dbd._tcp`

**Comment by edison-moreland** [comment]
Is this still an issue? I could work on a fix for it

**Comment by tadly** [comment]
It very much is still an issue, yes.
The problem however is not creating a fix (that's rather easy as stated by OP) but more whether or not this will/should be added to the library as those service names aren't RFC compliant.

From where I stand, I think it's an acceptable change as it doesn't break anything or harm anyone.
Not like this suddenly causes security risks or anything. :)

**Comment by tadly** [comment]
@jstasiak @stephenrauch 
This issue is over a year old at this point.
Would a PR get merged?
I still rely on patching it myself on every system which is kind of annoying.

**Comment by jstasiak** [comment]
0.21.0 (released just now) should take care of this.

**Comment by tadly** [comment]
I just realized that this is still an issue when e.g. the `ServiceBrowser` is used as it [validates the name without allowing underscores](https://github.com/jstasiak/python-zeroconf/blob/af33c83e72d6fa4171342f78d15b2f28038f1318/zeroconf.py#L1273).

This might also become an issue with other parts (e.g. the `ServiceInfo` class).

Especially with the `ServiceBrowser`, `allow_underscores` should default to `True`. Not sure if the class itself should expose this as an option (in it's `__init__`)

**Comment by jstasiak** [comment]
Well this is embarrassing. I do have exactly the change you're talking about but I completely failed when it came to merging the whole thing to master. Expect a patch correcting this.

**Comment by jstasiak** [comment]
Ok, this time I really hope 0.21.3 handles it :)

**Comment by tadly** [comment]
My usecase seems to be working now, thanks :)
