### ISSUE TITLE
DNS compression type X is unknown at Y

### ISSUE THREAD

**Issue by LouisMT** [jstasiak/python-zeroconf#1038]
I'm using this library through the Home Assistant `zeroconf` integration. I just noticed that my Home Assistant logs are filled with thousands of messages from this library. They all are formatted like `DNS compression type X is unknown at Y`. For example:

```
DNS compression type 66 is unknown at 32
```

I have no idea where this is coming from, but I quickly added some extra logging to log the `data` field, hopefully that helps:

```python
b'\\x00\\x00\\x00\\x00\\x00\\x02\\x00\\x02\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x01\\x80\\x01\\xc0\\x0c\\x00\\x1c\\x80\\x01\\x10Tstat-3B55DC-148\\x04_hap\\x04_tcp\\x05local\\x00\\x00!\\x80\\x01\\x00\\x00\\x00\\xbb\\x00\\x08\\x00\\x00\\x00\\x00\\x00P\\xc0\\x0c\\xc0\\x18\\x00\\x10\\x80\\x01\\x00\\x00\\x00\\xbb\\x00E\\x14id=02:67:18:61:4E:72\\x0fmd=YT4710WF1003\\x06pv=1.0\\x04s#=1\\x04c#=7\\x04sf=0\\x04ff=1\\x04ci=9'
```

I'm not sure what's changed. Everything was working perfectly for the past few days. I'm running this library in Docker and I'm using `avahi-daemon` to replicate mDNS packets from my local network to my Docker containers.

Please let me know if you need any additional info.

**Comment by bdraco** [comment]
Thats not a valid type so its a corrupt packet.  There isn't anything we can do about bad wire data
