### ISSUE TITLE
% formatted strings

### ISSUE THREAD

**Issue by torsj** [jstasiak/python-zeroconf#1056]
Several modules have problems with the old printf style string formatting with the %.
The problem is that the "," after the string should be a "%" and the parameter list should be a tuple.

See for instance in _core.py at line 289:

```
log.debug('Received from %r:%r [socket %s]: (%d bytes) [%r]' ,
                addr,  port, self.sock_description, data_len, data, )
```
It should have been:

```
log.debug('Received from %r:%r [socket %s]: (%d bytes) [%r]' %
    (addr, port, self.sock_description, data_len, data) )
```

I found this problem in _core.py, _handlers.py, _protocol.py and _utils/net.py when I tried to solve
a problem with a busy port 5353. The log file was difficult to read without most of the necessary data.

**Comment by Jc2k** [comment]
Thats how the python logging module is supposed to work. See this example from the python docs:

https://docs.python.org/3/howto/logging.html#logging-variable-data

```
import logging
logging.warning('%s before you %s', 'Look', 'leap!')
```

One of the reasons for this is you can delay doing the string substitutions for a logger that isn't active. When you have lots of log.debug all those string substitutions can get slow. So the logging module defers them. Thats why its bad practice to use f-strings with python logging.

If its not working its for a different reason than not using `%`.

**Comment by bdraco** [comment]
Jc2k is spot on.  This is by design.
