### ISSUE TITLE
No module named zeroconf

### ISSUE THREAD

**Issue by Techassi** [jstasiak/python-zeroconf#106]
Hi guys,
I use your browser script to detect services in my network.
Suddenly my script doesn't work anymore because python throws an ImportError: No module named zeroconf.

But it is installed and I even tried to uninstall and reinstall it. Didn't change the outcome.
Hope you can help me with this.

**Comment by jstasiak** [comment]
Hi, there are few things to figure out here:

1. You say "Suddenly my script doesn't work anymore" - this implies it used to work, what changed? Have you upgraded the package? Restarted the application? Something else?
2. What Python are you using and what's the zeroconf package version (``pip freeze | zeroconf``)?
3. Can you show the output of the following Python program (the code assumes Unix-like environment)?

```python
import sys
import subprocess
file = [f for f in sys.path if 'site' in f][0] + '/zeroconf.py'
subprocess.check_call(['ls', '-lah', file])
```

**Comment by Techassi** [comment]
Hi,

1. I upgraded it at some point

2. I am using `python3 `and my zeroconf version is `0.19.1`
3. The output of your code is: `IndexError: list index out of range`

**Comment by jstasiak** [comment]
I feel that there's something funny about your Python installation, would you mind executing the following and providing the output?

1. ``python3 -c 'import pprint; import sys; pprint.pprint(sys.path)'``
2. ``pip -v uninstall -y zeroconf; pip -v install zeroconf``

**Comment by Techassi** [comment]
I will do that. Gimmie a sec

**Comment by Techassi** [comment]
1. `['',
 '/usr/lib/python3.4', 
 '/usr/lib/python3.4/plat-arm-linux-gnueabihf',
 '/usr/lib/python3.4/lib-dynload',
 '/usr/local/lib/python3.4/dist-packages',
 '/usr/lib/python3/dist-packages']
`
2. `Uninstalling zeroconf:
  Removing file or directory /usr/local/lib/python3.4/dist-packages/__pycache__/zeroconf.cpython-34.pyc
  Removing file or directory /usr/local/lib/python3.4/dist-packages/zeroconf-0.19.1.dist-info/DESCRIPTION.rst
  Removing file or directory /usr/local/lib/python3.4/dist-packages/zeroconf-0.19.1.dist-info/METADATA
  Removing file or directory /usr/local/lib/python3.4/dist-packages/zeroconf-0.19.1.dist-info/RECORD
  Removing file or directory /usr/local/lib/python3.4/dist-packages/zeroconf-0.19.1.dist-info/WHEEL
  Removing file or directory /usr/local/lib/python3.4/dist-packages/zeroconf-0.19.1.dist-info/metadata.json
  Removing file or directory /usr/local/lib/python3.4/dist-packages/zeroconf-0.19.1.dist-info/pbr.json
  Removing file or directory /usr/local/lib/python3.4/dist-packages/zeroconf-0.19.1.dist-info/top_level.txt
  Removing file or directory /usr/local/lib/python3.4/dist-packages/zeroconf.py
  Successfully uninstalled zeroconf
Downloading/unpacking zerocon
  Could not fetch URL https://pypi.python.org/simple/zerocon/: 404 Client Error: Not Found
  Will skip URL https://pypi.python.org/simple/zerocon/ when looking for download links for zerocon
`

I discovered somethin weird. The code won't execute past this point above. It just gets stuck. Also i have to use `pip3` instead of `pip`

**Comment by jstasiak** [comment]
It seems that you're not using virtualenv, is that correct? Installing packages with pip system-wide is known to cause troubles. Can you retry with a virtualenv?

**Comment by Techassi** [comment]
Ok I never heard about virtualenv. Can you give me some information how to set it up!

**Comment by Techassi** [comment]
Ok I got it working now with virtualenv!
