### ISSUE TITLE
Split does not take named parameters

### ISSUE THREAD

**Issue by sistemicorp** [jstasiak/python-zeroconf#1067]
Came across an error when code was compiled with `Nuitka`,

```
  File "/tmp/.mount_p1125_OejYxm/zeroconf/_logger.py", line 27, in <module zeroconf._logger>
TypeError: str.split() takes no keyword arguments
```
From doing some research, seems `spilt()` no longer takes named parameters(?).  [Reference.](https://stackoverflow.com/questions/11716687/why-does-str-split-not-take-keyword-arguments)

From `_logger.py`,
```python
log = logging.getLogger(__name__.split('.', maxsplit=1)[0])
```
Removing `maxsplit=` resolved my issue.

Python 3.10, Ubuntu 20.4, Nuitka 0.8rc9, zeroconf 0.38.4 (seems 0.38.5 has same code).

**Comment by jstasiak** [comment]
It's a Nuitka issue

```
>>> import sys
>>> sys.version
'3.10.2 (main, Feb  2 2022, 05:51:25) [Clang 13.0.0 (clang-1300.0.29.3)]'
>>> "a b c".split(maxsplit=1)
['a', 'b c']
```

**Comment by sistemicorp** [comment]
Indeed.  I see *now* that named parms are still part of the official split API.
Sorry for the spam.
