### ISSUE TITLE
Question, service browsing/discover without dependencies?

### ISSUE THREAD

**Issue by gepd** [jstasiak/python-zeroconf#107]
I'm developing a plugin for **Sublime Text** who needs to discover the availables devices. I've been working for a while with `zeroconf` but there have been somes problems because ST runs the plugins in their own simplified version of python, so I've tried many ways to improve the installation of this library. 

The last try was to download it with all dependecies, but netifaces is a library harder to make ir run because is a C library.

So my question is; There is a way to browse a service without all the dependencies, which ones are required by this feature? My idea is to make a lightweight version to only discover services.

I'll really appreciate any help/ advice.

**Edit:** I've tried with the others zeroconf repositories (paulsm, wmcbrine) who seems to not need netifaces dependencies, but it doesn't recognizes the same services than this repo

**Comment by stephenrauch** [comment]
As I mentioned over at [Stackoverflow](https://stackoverflow.com/questions/44610435/minimun-code-for-mdns-browsing), if you look through the code, I think you will find that the dependencies are there to make it possible to deal with a wider range of environments, and that they can be removed.  This is the beauty of Open Source. 

The dependencies are not extensive.  You should be able to remove them, fairly easily, if you understand your particular environment, and can replace the calls into the the dependent libraries, with something appropriate for your environment.

Alternatively, you could build your own ```netifaces``` for Sublime, that only implements the needed pieces.  Again, they are not extensive.

**Comment by gepd** [comment]
Thanks @stephenrauch I did not realize it was you in stackoverflow, I just wanted to make sure that netifaces are not extensive.

Thanks again
