### ISSUE TITLE
ServiceBrowser callback on update

### ISSUE THREAD

**Issue by emontnemery** [jstasiak/python-zeroconf#112]
ServiceBrowser is only issuing callbacks when an entry is added or removed, but not when it is updated.
Two very simple ways to address this:
Modify ServiceBrowser.update_record to enqueue an 'Added' callback each time the entry is updated.
Add new callback, ServiceStateChange.Added, and call when an entry is updated.

I'd be more than happy to implement this and submit a PR, but wanted to know what solution would be appropriate.

**Comment by bdraco** [comment]
@emontnemery since `ServiceStateChange.Updated` exists, this seems solved.
