### ISSUE TITLE
Threading bug

### ISSUE THREAD

**Issue by sedwards2009** [jstasiak/python-zeroconf#115]
There appears to be a threading bug. This is the exception:

```
Exception in thread zeroconf-ServiceBrowser__ultimaker._tcp.local.:
Traceback (most recent call last):
File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
self.run()
File "/usr/lib/python3/dist-packages/zeroconf.py", line 1161, in run
for record in self.services.values():
RuntimeError: dictionary changed size during iteration
```

Looking at the code is appears that if the `ServiceBrowser` is busy looping over `self.services` in `run()` and at the same time the other thread (zeroconf engine?) calls `ServiceBrowser.update_record()`, then the size of the `ServiceBrowser.services` dict can change.

A simple `threading.Lock` to guard access to `ServiceBrowser.services` is likely to be enough.

**Comment by bdraco** [comment]
This is fixed on upstream/master
