### ISSUE TITLE
Handling Name Conflicts

### ISSUE THREAD

**Issue by schulz-m** [jstasiak/python-zeroconf#119]
I just started using this library and I realised that when I run the `registration.py` script in the examples, the library doesn't seem to handle name conflicts, i.e. it doesn't create a new service entry on the records - I assume developers have to implement name conflict resolution themselves then?

**Comment by bdraco** [comment]
Newer version have a `allow_name_change = True` option:

https://python-zeroconf.readthedocs.io/en/latest/api.html#zeroconf.Zeroconf.register_service
