### ISSUE TITLE
Examples don't seem to be working

### ISSUE THREAD

**Issue by esazhin** [jstasiak/python-zeroconf#12]
I have copied the examples and using the released version 0.15.1, but the the browser methods add_service(), remove_service() neither their forms addService() removeService() are not working - there is no callback happening. Without those examples it is unclear what needs to be done to be able to use the library. 

I'm creating a virtual env and installing zeroconf wheel using pip. Python-3.4.1 Starting browser and 
I'm tried both ip as in examples for the registration and also actual IP socket.inet_aton(socket.gethostbyname(socket.gethostname())) on port 5555

Please advise!

Thanks!

**Comment by jstasiak** [comment]
@esazhin @jantman Can you test current master (af5e363) and tell me if your issues persist?

**Comment by esazhin** [comment]
just saw the update: will try to get to it in near future - loaded with some other stuff, sorry.

**Comment by jstasiak** [comment]
I'll close as I believe https://github.com/jstasiak/python-zeroconf/commit/af5e363e7fcb392081dc98915defd93c5002c3fc has fixed this - please reopen if you can reproduce the issue with the latest code.
