### ISSUE TITLE
Supporting unicast queries

### ISSUE THREAD

**Issue by machinekoder** [jstasiak/python-zeroconf#121]
DNS-SD over multicast is great for discovering services on the local network. However, in some instances it does not work, this includes a broken router, a network interface that does not support multicast, WANs and so on.

At least with avahi as server one has the opportunity to send DNS-SD queries via unicast to port 5353. This is great when multicast fails. Does python-zeroconf already support this?

If not I think it might be easy to add python-zeroconf already support DNS-SD very well and adding a unicast sender might be enough.

JDNS does support DNS-SD over unicast for example: https://github.com/psi-im/jdns

**Comment by machinekoder** [comment]
I imagine something like:

`Zeroconf(nameservers=['192.168.7.2'], mode=Unicast)`

**Comment by bdraco** [comment]
This was done on upstream/master
