### ISSUE TITLE
Python2 support has been quietly dropped

### ISSUE THREAD

**Issue by machinekoder** [jstasiak/python-zeroconf#122]
Python2 and 3.3 support has been dropped: https://github.com/jstasiak/python-zeroconf/commit/f22f421e4e6bf1ca7671b1eb540ba09fbf1e04b1

But Python2 is still live and active and widely used. Dropping support is not a good idea in my opinion.

However, what really annoyed me is, that there is no warning that this version python-zeroconf doesn't support Python2, instead one get's random error messages. Cost me quite some time, as I assumed an error in my code.

I suggest adding an import error for Python 2 and 3.3.

**Comment by jstasiak** [comment]
Hey, I appreciate your position, but this is a documented[1] change.

[1] https://github.com/jstasiak/python-zeroconf/commit/f22f421e4e6bf1ca7671b1eb540ba09fbf1e04b1#diff-88b99bb28683bd5b7e3a204826ead112R123

**Comment by machinekoder** [comment]
Good point, I should have looked into the changelog.

**Comment by tlc** [comment]
Yet pip for python 2 installs 0.20.0 which is broken.  Can pip be informed of different versions for python2 and python3.
