### ISSUE TITLE
Resolving names isn't ASCII-case-insensitive

### ISSUE THREAD

**Issue by smcv** [jstasiak/python-zeroconf#128]
Service names are DNS labels, which are defined by the DNS RFCs to be case-insensitive within the ASCII range: `A` == `a` (although not outside that range: `Á` != `á`), but python-zeroconf doesn't fully implement this. (There are a few `lower()` calls, but not enough to make everything work.)

Steps to reproduce:
* `avahi-publish-service -s 'MY SERVICE NAME' _test._tcp 0`
* Run the new `./examples/resolver.py` from #127

Expected result:
* The resolver finds `MY SERVICE NAME`, treating it as a valid answer to the question "where is `My Service Name`?", and prints its `ServiceInfo`

Actual result:
* The resolver waits for a reply and then prints `None`

**Comment by smcv** [comment]
A work-in-progress branch at https://github.com/smcv/python-zeroconf/commits/case-insensitive adds minimal support for case-insensitive names.

Caveats:
* I haven't added NFC canonicalization, for instance converting (U+0301 COMBINING ACUTE ACCENT, U+0061 LATIN SMALL LETTER A) in a ServiceInfo's name into U+00E1 LATIN SMALL LETTER A WITH ACUTE.
* I'm still using `str.lower()` for keys rather than the more correct `str.translate(string.maketrans(string.ascii_uppercase, string.ascii_lowercase))`. Or perhaps the `key` should be a `bytes` object so zeroconf can use `bytes.lower()`? That would also avoid accidentally comparing un-normalized strings with normalized strings.
* `ServiceInfo.server` is compared case-sensitively, although in practice it comes from the remote publisher, so as long as the publisher is consistent about how it publishes a name, we're OK.
* The keys are recalculated repeatedly rather than being memoized. `name` and `server` would need to become properties with a non-trivial setter if they're going to be memoized.
* I'm not sure whether making `DNSEntry.__eq__` case-insensitive will have unwanted side-effects. Perhaps the case-insensitivity should be implemented in a new `DNSEntry.matches(other)` method that treats `self` as a pattern and tests whether `other` matches that pattern, instead?

**Comment by bdraco** [comment]
This is fixed on upstream/master
