### ISSUE TITLE
how to handle multiple address fields?

### ISSUE THREAD

**Issue by cyberic99** [jstasiak/python-zeroconf#132]
Hi

I have an application that advsertises its services.
The host running the application has multiple IP addresses.

When getting the service info, the address field contains only one of these addresses, not all of them...

How can I get a list of addresses instead?

Thank you

**Comment by dtantsur** [comment]
Will https://github.com/jstasiak/python-zeroconf/pull/170 solve your problem?

**Comment by cyberic99** [comment]
yes I think so

Once the changes are committed into the master branch, will I be able to upgrade my version using pip?

**Comment by dtantsur** [comment]
You'll have to wait for a new version to be released.

**Comment by Kane610** [comment]
@dtantsur not sure if I understand this issue right. But I have some network cameras that broadcast multiple addresses for the same service, link local and ordinary address. And it seems to be a bit of a lottery which address gets picked up by this library. And I've tried this with 0.23 as well, which seem to have the same behaviour.

Is my issue the same as this issue or should I create a new one?

**Comment by stashlukj** [comment]
I have the same problem with 0.23.0. It will even give an address for a different adapter.

**Comment by dtantsur** [comment]
Could somebody paste an example code for this issue please?

**Comment by om26er** [comment]
> Could somebody paste an example code for this issue please?

Please run below code multiple times and you will notice how the address gets randomly picked and for all interfaces its the same
```python3
import zeroconf
import socket

zconf = zeroconf.Zeroconf()
SERVICE_IDENTIFIER = 'deskconn'
addrs = [socket.inet_pton(socket.AF_INET, address) for address in zeroconf.get_all_addresses()]
service = zeroconf.ServiceInfo(type_=f"_{SERVICE_IDENTIFIER}._tcp.local.", name=f"{socket.gethostname()}._{SERVICE_IDENTIFIER}._tcp.local.", addresses=addrs, port=5000)

zconf.register_service(service)
zconf.unregister_all_services()
```

**Comment by khan-git** [comment]
@om26er I see the same behaviour.
One interesting behaviour thou was that the first time I register a service Zeroconf publishes the correct address on the right interface.
Unpublishing and publishing again within x minutes/seconds will give the random behaviour.
If I wait for around 15+ minutes it will publish correctly again and the following times do randomly again.

**Comment by khan-git** [comment]
@om26er If your do not set the `addresses` parameter it should publish the correct address to the correct interface.

**Comment by novirium** [comment]
> @om26er If your do not set the `addresses` parameter it should publish the correct address to the correct interface.

Is this actually true? This is exactly the behaviour I (and I'm assuming @om26er) would like to use, and yet if I omit the `addresses` parameter other devices fail to resolve an IP for the service at all.

**Comment by webdevbyjoss** [comment]
I've tried omitting the `addresses` parameter and my devices fail to resolve the IP address as well, did you actually managed to get it working?

**Comment by novirium** [comment]
No, I didn't - I wound up scanning through the available interfaces (using `ifaddr`, the same method `python-zeroconf` uses), filtering which ones I wanted to advertise my service on, and individually doing a registration for each of them - providing the correct address for each interface. A loop then periodically checked to see if the interfaces had changed, and re-registered things if necessary.

Looking through the source of `python-zeroconf` though, it looks like the desired behaviour (automatically providing an A record that points to the device IP address on whatever interface the request came in on) isn't possible without restructuring a fair bit of it - I think it's unlikely such a feature would be added.

**Comment by bdraco** [comment]
This has been fixed on `master`
