### ISSUE TITLE
[Performance] 0.20.0 Seems to be more CPU-intensive than 0.17.6 on Mac OS X

### ISSUE THREAD

**Issue by LipuFei** [jstasiak/python-zeroconf#133]
**OS:** Mac OS X
**Version:** 0.20.0
**Python version:** 3.5.2

On a LAN with more than 100 devices that broadcast mDNS messages, zeroconf 0.20.0 seems to be way more CPU-intensive than 0.17.6. We have integrated zeroconf with an Qt-based GUI application. When it's idle, the process still has high busty CPU usage; when I disconnect all network connects or disable zeroconf completely, the CPU usage goes quiet. Please see the charts below:

**Application idle, zeroconf on, network on**:
![image](https://user-images.githubusercontent.com/2630468/40906822-4e09e9bc-67e2-11e8-9e75-4ae811116fcd.png)

**Application idle, zeroconf off/network off**:
![image](https://user-images.githubusercontent.com/2630468/40906865-701c0094-67e2-11e8-9b46-81c6fd3a3ab6.png)

When I switch to 0.17.6, although the CPU usage is still busty, the application GUI seems way more responsive than when I used 0.20.0.

**Comment by Ghostkeeper** [comment]
Also occurs in Windows 10 and Ubuntu 18.04.

The application we are encountering this in is Cura. The relevant code starts here: https://github.com/Ultimaker/Cura/blob/415763655279494b133f016581b576495d935b35/plugins/UM3NetworkPrinting/UM3OutputDevicePlugin.py#L96

**Comment by fieldOfView** [comment]
Is this fully fixed now that https://github.com/jstasiak/python-zeroconf/pull/205 has been merged?

**Comment by LipuFei** [comment]
> 
> 
> Is this fully fixed now that #205 has been merged?

It's fixed.
