### ISSUE TITLE
zeroconf 0.21.0 claims python 3.4+, but imports typing

### ISSUE THREAD

**Issue by rtobar** [jstasiak/python-zeroconf#139]
Hi,

The newest zeroconf release still claims python 3.4+ compatibility, but it actually fails to import on python 3.4+. The Travis builds pass because ``typing`` is installed as part of the ``requirements-dev.txt`` file, but when using a pure installation ``typing`` isn't included.

Would it be possible to have a new release that either: a) drops 3.4 support, or b) adds the ``typing`` module when being installed under 3.4? I can provide a patch for the latter if required.

**Comment by jstasiak** [comment]
Hey, yes, sorry about that. A patch would be appreciated.

**Comment by jstasiak** [comment]
Just released 0.21.1 fixes this.
