### ISSUE TITLE
close() takes 5 seconds

### ISSUE THREAD

**Issue by antonio-fiol** [jstasiak/python-zeroconf#143]
The call to `zeroconf.close()`, e.g. from the `browser.py` example, takes 5 seconds to return.
The time is spent in `self.engine.join()` because the Engine is inside `select.select(rs, [], [], self.timeout)`.
At least on Linux 3.13.0, closing the socket does not wake the Engine up, even if I added `rs` to the third parameter of `select.select`.
So I believe that the only option might be something like https://stackoverflow.com/questions/4660756/interrupting-select-to-add-another-socket-to-watch-in-python but I know that the example as-is might break Windows compatibility.
Since I do not use Windows, I can not test it there.
I'm submitting a patch using the above os.pipe() approach that I tested and works for me.
[zc_close.patch.zip](https://github.com/jstasiak/python-zeroconf/files/2423988/zc_close.patch.zip)

**Comment by kiplingw** [comment]
Hey @antonio-fiol. Thanks for reporting this. I am not an upstream maintainer, but I am also experiencing this same issue. The `close()` method appears to be taking too long to execute.

Would you consider submitting your patch as a pull request? This may assist the maintainers in testing and getting it into the repository faster in my experience.

**Comment by antonio-fiol** [comment]
Hi @kiplingw, I did not create a pull request because my patch would likely break the software completely on Windows platforms, which is in my opinion an undesirable side effect. And I did not know whether the problem exists on Windows or not, and/or how to solve it for Windows.
If you (or anyone else) is willing to test it on Windows, I'd be happy to work with you on this one and create a pull request that fixes the problem in a cross-platform way.

**Comment by kiplingw** [comment]
Thanks @antonio-fiol. Unfortunately I don't use Windows. But for the sake of portability, patches should strive to maintain portability whenever possible.

**Comment by cyberic99** [comment]
Yeah I was annoyed by this delay too...

What I do for now is:
```python
     zeroconf = Zeroconf()
     zeroconf.engine.timeout = 1
```
but it is only a hack

**Comment by kiplingw** [comment]
That does work, but affects all of the work Zeroconf does. If you set the timeout to 1 just before calling close(), then it's too late and its internal threading / message loop uses whatever it started with.

**Comment by jstasiak** [comment]
I think having an extra socket and using it to interrupt select could be a solution here.

> At least on Linux 3.13.0, closing the socket does not wake the Engine up, even if I added rs to the third parameter of select.select

This is (unfortunately) expected on Linux and likely on some of the other supported platforms (from https://linux.die.net/man/2/select):

> Multithreaded applications
> If a file descriptor being monitored by select() is closed in another thread, the result is unspecified. On some UNIX systems, select() unblocks and returns, with an indication that the file descriptor is ready (a subsequent I/O operation will likely fail with an error, unless another the file descriptor reopened between the time select() returned and the I/O operations was performed). On Linux (and some other systems), closing the file descriptor in another thread has no effect on select(). In summary, any application that relies on a particular behavior in this scenario must be considered buggy.

**Comment by cyberic99** [comment]
> If you set the timeout to 1 just before calling close(), then it's too late and its internal threading / message loop uses whatever it started with.

I set it just after instanciating Zeroconf

**Comment by kiplingw** [comment]
Yes, I'm aware of that. But I'm not sure if doing so will degrade successful service discovery functionality.

**Comment by cyberic99** [comment]
Is there a way to add a method to send something to the socket, so that would stop the ``select()`` ?

**Comment by bdraco** [comment]
use a self-pipe in the select and write to it to unblock the select on close.

**Comment by jstasiak** [comment]
This has been fixed by https://github.com/jstasiak/python-zeroconf/pull/243.
