### ISSUE TITLE
No services discovered Centos

### ISSUE THREAD

**Issue by rkbennett** [jstasiak/python-zeroconf#155]
Been trying to find devices and service types via the examples on the README, zeroconf is unable to find pretty much anything

OS: CentOS 7
Python: 3.6
 
Been banging my head against this for a bit, any help would be appreciated

**Comment by bdraco** [comment]
Looks like this is still open.  Did you figure out the issue?

**Comment by bdraco** [comment]
This has gone stale. I'm going to close it out
