### ISSUE TITLE
Exception when import module

### ISSUE THREAD

**Issue by AnreyFlyAway** [jstasiak/python-zeroconf#156]
Hello!

I saw an error, when I just try to import the zeroconf module.

Text of excpetion:

`Traceback (most recent call last):                              
  File "<stdin>", line 1, in <module>                           
  File "C:\Python27\lib\site-packages\zeroconf.py", line 175    
    def current_time_millis() -> float:                         
                              ^                                 
SyntaxError: invalid syntax                                     
>>> from zeroconf import ServiceBrowser, Zeroconf               
Traceback (most recent call last):                              
  File "<stdin>", line 1, in <module>                           
  File "C:\Python27\lib\site-packages\zeroconf.py", line 175    
    def current_time_millis() -> float:                         
`
If I am not mytaken this syntaxis " def current_time_millis() -> float: "    used only for python3.X, but I use Python2.7 and after updating by pip I saw this error.

I dont know what should I do with this, just clone repo to previous commit? 

I use Ubunut x64, Python 2.7

**Comment by jstasiak** [comment]
If you want to use Python 2 you need to install the version 0.19.1 (or earlier) of this package, starting with 0.20.x only Python 3.4+ is supported. See https://github.com/jstasiak/python-zeroconf/issues/122

**Comment by AnreyFlyAway** [comment]
Ok, thank you. But I installed it from pip, isn't it an error?

**Comment by jstasiak** [comment]
No. if you do simply `pip install zeroconf` it'll fetch the latest version from PyPI. The latest version is Python 3.4+-only. If you want an earlier, Python 2-compatible version, you need to specify it explicitly.

**Comment by AnreyFlyAway** [comment]
Yes, I understood and thank you for answer. But I thought it is wrong, when you call "python2 -m pip install zeroconf" and installation finishes success. At least thera are information abtout this in readme.

**Comment by jstasiak** [comment]
Oh, sorry. Yes, that could be improved.
