### ISSUE TITLE
Confusion about repeat broadcasts

### ISSUE THREAD

**Issue by jantman** [jstasiak/python-zeroconf#16]
I'm a bit confused by the examples, specifically where they start waiting.

If I start the `browser.py` example on one host on my LAN and then start `registration.py` on another, the output from `browser.py` shows the discovery of the `Paul's Test Web Site._http._tcp.local.` service as I expect (as well as a bunch of other services from devices on my LAN).

However, if I start `registration.py` first, wait 30 seconds or so, and then run `browser.py`, the output of `browser.py` shows a bunch of services from other devices on my network (Brother printer, RaspBMC on a RaspberryPi, etc.) but never shows the `Paul's Test Web Site._http._tcp.local.` service.
1. With the logging I added (https://github.com/jantman/python-zeroconf/tree/more_logging) I see that `browser.py` is sending an outgoing request (`Sending: DNSOutgoing( QUESTIONS: question[ptr,in,_http._tcp.local.]) (addr=224.0.0.251 port=5353)`) which the other services on my LAN respond to, but `registration.py` doesn't seem to be. Is there something amiss in the example? After the initial call to register_service() it doesn't seem to be listening for or responding to queries (or maybe this is just a bug with threading and how I'm trying to do logging?)
2. Shouldn't `register_service()` be rebroadcasting the DNS at regular intervals? Or is this something that I have to do manually?

**Comment by jstasiak** [comment]
I'll need to read the code too as I'm not familiar with that part, I'll get back to you soon.

**Comment by jstasiak** [comment]
@jantman Unfortunately I can't reproduce the issue you described. I'm on OS X so this may be relevant, I'll test on Ubuntu when I get the chance.

**Comment by bitcraft** [comment]
I have this problem as well.  It seems that there is a window of time where the listener will 'see' the service, but after that it no longer works.  This behavior seems to only be an issue with the listener.  Using a 3rd party bonjour browser, I can find the service created with zeroconf.  FWIW, it also seems to cause the windows tool "bonjour browser" to hang, so I suspect there are parts incorrectly implemented (or not at all) in zeroconf that are related.

This is tested on OS X and Windows.

**Comment by jantman** [comment]
@jstasiak sorry, but the project that I was using this for has been shelved indefinitely, and I don't think I can even get my test environment running again without a major time investment. I don't think that I'm going to be able to contribute any more to this issue unless I happen to pick up the project again.

**Comment by bdraco** [comment]
Looks like this has gone stale
