### ISSUE TITLE
unregister_all_services() causes suspicious service adds

### ISSUE THREAD

**Issue by keepsimple1** [jstasiak/python-zeroconf#178]
Similar to an old issue: #34 ,  with latest zeroconf 0.23.0, I still see the issue:  when `zero_conf.unregister_all_services()` is called, other browsers would receive both `remove_service` and `add_service` events,  and the `add_service` event has a later timestamp (about 6ms later).

If I change to use `zero_conf.unregister_service()`,  other browsers do not see `add_service` event but they are not getting `ServiceInfo` object in their `remove_service` callback.

**Comment by jstasiak** [comment]
There's been some fixes in this area – can you test with zeroconf 0.27.0?

**Comment by jstasiak** [comment]
I'll assume this is fixed by 0.27.0, please reopen if not.
