### ISSUE TITLE
Feature request: Running on a different port

### ISSUE THREAD

**Issue by David-Baddeley** [jstasiak/python-zeroconf#186]
We use zeroconf to discover different components of a custom, ad-hoc, distributed computing solution, but are running into performance issues on crowded networks due to the amount of mDNS traffic. One attractive solution (for us) would be to run the zeroconf protocol on a non-standard port, meaning that we should only get the traffic we are interested in. 

As it stands we have 2 possible courses of action - maintain our own copy of zeroconf with the `_MDNS_PORT` constant changed, or try and make _MDNS_PORT something that could be changed (my preference would be an attribute of the `Zeroconf` class) programatically and to submit a PR. This issue is an attempt to gauge the degree of interest in the latter.

**Comment by jstasiak** [comment]
I think having the port configurable would be a cool feature.

PS. Would you be willing to run your application with a profiler to see what's causing the performance issues inside the `zeroconf` module? Maybe try to find some hotspot(s) with https://github.com/rkern/line_profiler? It'd be great to see what could be improved on this front.

**Comment by bdraco** [comment]
@David-Baddeley Are you still seeing performance issues on `master`?

**Comment by David-Baddeley** [comment]
It's a bit embarrassing, but I'm still pinned at a really old version of
zeroconf (initially to keep py2 compatibility in our codebase). Have been
meaning to revisit for around a year now.

I never did track down the source of my initial problems (which, based on
some limited wireshark logging, I suspect was a poorly implemented 3rd
party mdns implementation somewhere on the network).

Many thanks,
David

**Comment by bdraco** [comment]
I'm going to close this since the performance issues should be fixed on `master`. Please reopen if you find thats not the case after updating.
