### ISSUE TITLE
Non-functional on MacOS (unable to query self)

### ISSUE THREAD

**Issue by quuu** [jstasiak/python-zeroconf#187]
Currently trying to register and browse for the same network, but the examples don't work. Running on MacOS Mojave (10.14) 

They worked when I first installed the package via pip3, but after playing around with the discovery and service registration, even `dns-sd -B` doesn't detect it anymore. 

Running `self_test.py` I get a failure at "Testing query of own service"

![image](https://user-images.githubusercontent.com/32676955/65068147-0bce6000-d956-11e9-8436-b40c5eb1e179.png)

**Comment by jstasiak** [comment]
It's working fine for me (`zeroconf` 0.26.0+, Mac OS 10.14.6, Python 3.8.2), I can't reproduce this. Is it still happening to you?

**Comment by timephy** [comment]
Works for me too

**Comment by jstasiak** [comment]
I'll close this – please reopen if you can provide some way to reproduce this.
