### ISSUE TITLE
pip and github do not have the same code for same version

### ISSUE THREAD

**Issue by Jicehef** [jstasiak/python-zeroconf#197]
version 0.23.0 on pip does not have 'IPVersion' whereas it is present on github's version with same version number...

**Comment by dtantsur** [comment]
Hi! I fetched https://github.com/jstasiak/python-zeroconf/archive/0.23.0.tar.gz and it does not seem to have IPVersion (as expected). Which file did you check?

**Comment by jstasiak** [comment]
I think this is about the master branch having `IPVersion` and version equal to 0.23.0 because there's been no new release? If so this is not really a huge issue I think, we can't bump a version with every single change after all (unless we automate it somehow).

**Comment by jstasiak** [comment]
Gonna close this, please reopen if I misread the report.
