### ISSUE TITLE
Try to merge the opendrop changes back

### ISSUE THREAD

**Issue by jstasiak** [jstasiak/python-zeroconf#198]
The opendrop changes are described as

> We use a modified version of the python-zeroconf package (essentially adding rudimentary IPv6 and AWDL support) 

Since we have IPv6 support of our own now there may be some conflict but looking at the changes it shouldn't bee too bad to handle. I pushed a branch based on version 0.20.0 since that's the version opendrop seems to have used and I applied their version on top of it. This is the commit: https://github.com/jstasiak/python-zeroconf/commit/5db003ca3eaf336257421d53e4b39f585b9f5d41 (https://github.com/jstasiak/python-zeroconf/tree/opendrop-before-rebase branch).

What we need to do is to rebase the commit on top of the current master branch, decide what we need to keep and resolve conflicts. If we decide against some of the opendrop changes maybe we could send a pull request to opendrop to make everyone happy?

**Comment by schmittner** [comment]
I've just checked out the v0.24.1 and started merging this with OpenDrop. The IPv6 supports seems pretty good and the only thing that I needed to change was to add support for AWDL. I've created a merge request #207. If this makes it into a release, I can update OpenDrop and close https://github.com/seemoo-lab/opendrop/issues/14.

**Comment by schmittner** [comment]
I think this can be closed now. Would appreciate if you could push a new release soon.

**Comment by jstasiak** [comment]
Yeah I'll make a release within an hour or so.

**Comment by jstasiak** [comment]
Released as part of version 0.24.2. Thanks for the patch!
