### ISSUE TITLE
Local test shows test_lots_of_names (zeroconf.test.Names) ERROR

### ISSUE THREAD

**Issue by humingchun** [jstasiak/python-zeroconf#204]
I have tried to create a local testing environment, and find that test_lots_of_names failed (please refer to attached screenshot). Is this OK for local test? I wonder why GitHub shows this repo's build status is passing.

All dev packages in requirements-dev.txt and mypy and black are installed.

Package             Version
------------------- ---------
appdirs             1.4.3
attrs               19.3.0
autopep8            1.4.4
black               19.10b0
certifi             2019.9.11
chardet             3.0.4
Click               7.0
coverage            4.5.4
coveralls           1.8.2
docopt              0.6.2
entrypoints         0.3
flake8              3.7.9
flake8-import-order 0.18.1
flake8-polyfill     1.0.2
idna                2.8
ifaddr              0.1.6
mccabe              0.6.1
mypy                0.740
mypy-extensions     0.4.3
nose                1.3.7
pathspec            0.6.0
pep8-naming         0.9.1
pip                 19.2.3
pycodestyle         2.5.0
pyflakes            2.1.1
regex               2019.11.1
requests            2.22.0
setuptools          41.2.0
toml                0.10.0
typed-ast           1.4.0
typing-extensions   3.7.4.1
urllib3             1.25.7

![test_error](https://user-images.githubusercontent.com/2714046/69727309-4118da80-115d-11ea-88fe-e97a265ca3b0.png)

**Comment by jstasiak** [comment]
Are you running Mac OS by any chance? See https://github.com/jstasiak/python-zeroconf/pull/194#issuecomment-547008005, I think you can ignore it locally right now.

**Comment by humingchun** [comment]
Oh yes, I am using Mac OS :-)
