### ISSUE TITLE
Addition of Type hints with List[Callable[..., None]] raises TypeError in Python 3.5.2

### ISSUE THREAD

**Issue by dannymeloy** [jstasiak/python-zeroconf#208]
Issue https://github.com/python/typing/issues/259 highlights an issue with Python 3.5.2:
"When using typing for Dict where key or value can be Callable which has Ellipsis in argument it leads to TypeError: 'ellipsis' object is not iterable."

Due to Ubuntu Xenial (and likely other platforms) being distributed with Python 3.5.2, this is an issue for a lot of platforms. Specifically the issue appears to be:
https://github.com/jstasiak/python-zeroconf/blob/f7715874c2242b95cf9815549344ea66ac107b6e/zeroconf/__init__.py#L1307

**Comment by jstasiak** [comment]
Thanks for the information. Do I understand it correctly that replacing all `Callable[..., None]` with `'Callable[..., None]'` (making annotations strings) is a workaround for this?

**Comment by dannymeloy** [comment]
Yes after a quick test, replacing each instance of a Callable with an ellipsis as a parameter with `'Callable[..., None]'` seems to resolve the issue 👍

**Comment by jstasiak** [comment]
This is fixed in the just released version 0.24.3.
