### ISSUE TITLE
remove_service being called unexpectedly

### ISSUE THREAD

**Issue by mattsaxon** [jstasiak/python-zeroconf#210]
I had some services where remove_service on MyListener was being called unexpectedly.

I debugged this and found that the reset_ttl method was not working as expected.

Whilst it was resetting the TTL, it was not recalculating the expiration time and therefore the record was expiring regardless that reset_ttl has been called.

I have provided a patch here https://github.com/jstasiak/python-zeroconf/pull/209

**Comment by jstasiak** [comment]
#209 has been released in version 0.24.4 just now.
