### ISSUE TITLE
Feature request: override the ServiceBrowser Thread name

### ISSUE THREAD

**Issue by cyberic99** [jstasiak/python-zeroconf#214]
Hi

Would it be possible to override the Zeroconf Service Browser thread name?

It is currently hardcoded to ``'zeroconf-ServiceBrowser_' + type_``, and it can be inconvenient or too long, when this name is used by loggers, for instance.

I know I can override it later with ``threading.currentThread().setName()``, but I'd prefer to set the name at init.

Thanks

**Comment by bdraco** [comment]
The size of the naming has been reduced￼
