### ISSUE TITLE
Subsequent calls to update do not trigger MyListener

### ISSUE THREAD

**Issue by mattsaxon** [jstasiak/python-zeroconf#215]
When zeroconf.update_service(info_service) is called multiple times, the subsequent updates don't trigger the Listener, but if you terminate the application and try again the information is visible (i.e. when Add Service is called, the properties (TXT record) is correct).

Note this doesn't always seem to occur and more investigation is required. I'm not sure at this stage if the behaviour is different with remote vs local interfaces

**Comment by mattsaxon** [comment]
@jstasiak I've further debugged this and have found it is due to the use of _CLASS_IN as opposed to _CLASS)N | _CLASS_UNIQUE records when broadcasting the service on the network, specifically, the TXT record.

Before further researching it would be good to know if python-zeroconf is designed to work with multiple services of the same name on the network? looking at zeroconf.handle_query() it looks like all the responses are unique, however in _broadcast_service() they are non unique.

Can you help me understand the expected behaviour of this module?

**Comment by mattsaxon** [comment]
I've looked a little further at this and read some of the specs.

It appears to me that all the A, SRV, TXT records that are being used in python-zeroconf should be unique records and only the PTR record should be shared/non-unique.

Assuming I'm right, there are a number of places in the code where this needs to be resolved, but it is fairly trivial to do so. Any comments welcome for those that know this codebase and/or mDNS better than I

**Comment by jstasiak** [comment]
@mattsaxon 

> Can you help me understand the expected behaviour of this module?

I wish I could help. This code is largely written by other people and my understanding of mDNS doesn't reach far enough for me to say anything conclusive here right now.

**Comment by mattsaxon** [comment]
Thanks @jstasiak, the code changes I've made are passing all existing tests, which is somewhat worrying in itself ;-)

So I think next step is to write some failing tests for the old code.

What may prove useful is that I have another implementation that I can compare the results with.

**Comment by mattsaxon** [comment]
I've read the IETF specs for mDNS and DNS-SD as well as looked through the python-zeroconf code.

I've convinced myself that the TXT, SRV and A/AAAA records should be unique.

Here's my PR to fix this https://github.com/jstasiak/python-zeroconf/pull/217

**Comment by mattsaxon** [comment]
I've posted a fix here https://github.com/jstasiak/python-zeroconf/pull/217

This changes all A/AAAA, SRV and TXT record to be of _CLASS_UNIQUE. 

This has the effect of setting the most signficant bit (which is the cache-flush bit) of the rrttype field. 

See https://tools.ietf.org/html/rfc6762#section-10.2 for a full explanation of this field and how it should be used.

Also used is the explanation of "shared" vs "unique" records in the later part of this section https://tools.ietf.org/html/rfc6762#section-2
