### ISSUE TITLE
0.24.4 isn't backward compatible?

### ISSUE THREAD

**Issue by AlexanderPavlenko** [jstasiak/python-zeroconf#216]
https://github.com/balloob/pychromecast/issues/332#issuecomment-570684042

**Comment by mattsaxon** [comment]
@jstasiak @jhogg, looks like we were the ones who made all the changes in that release. 

I've looked at the linked issue and can't see why mine would have caused the issue.

**Comment by jstasiak** [comment]
This has been resolved by https://github.com/home-assistant-libs/pychromecast/pull/337
