### ISSUE TITLE
Unable to use zeroconf in jail

### ISSUE THREAD

**Issue by dekimsey** [jstasiak/python-zeroconf#221]
I found I was unable to load the zeroconf module in my jail because the jail's IPs are aliased from the main device. If I monkey-patched the `get_all_addresses()` function to _not exclude_ "Host only netmasks" zeroconf would load. Admittedly this behavior could still be wrong, but at least the demo browser now runs.

Specifically I removed the `and addr.network_prefix != 32` statement from the list comprehension on `get_all_addresses()`

FreeBSD 12.1
Version: zeroconf-0.23.0

```
>>> zeroconf.Zeroconf(ip_version=IPVersion.V4Only)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/home/hass/.hass-venv/lib/python3.7/site-packages/zeroconf/__init__.py", line 2134, in __init__
    interfaces, unicast, ip_version, apple_p2p=apple_p2p
  File "/usr/home/hass/.hass-venv/lib/python3.7/site-packages/zeroconf/__init__.py", line 2056, in create_sockets
    interfaces = normalize_interface_choice(interfaces, ip_version)
  File "/usr/home/hass/.hass-venv/lib/python3.7/site-packages/zeroconf/__init__.py", line 1925, in normalize_interface_choice
    'No interfaces to listen on, check that any interfaces have IP version %s' % ip_version
RuntimeError: No interfaces to listen on, check that any interfaces have IP version IPVersion.V4Only
```

```
$ ifconfig
re0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=8209b<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM,WOL_MAGIC,LINKSTATE>
        ether bc:5f:f4:72:58:b1
        inet 192.168.10.14 netmask 0xffffffff broadcast 192.168.10.14
        media: Ethernet autoselect (100baseTX <full-duplex>)
        status: active
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
        options=680003<RXCSUM,TXCSUM,LINKSTATE,RXCSUM_IPV6,TXCSUM_IPV6>
        groups: lo
pflog0: flags=100<PROMISC> metric 0 mtu 33184
        groups: pflog
```

**Comment by mtdcr** [comment]
I had to apply the same modification in order to use zeroconf in Qubes. AFAICS, logically there's no relation between the netmask and multicast. In case zeroconf was trying to avoid using point-to-point interfaces, it would need a different test.

**Comment by jstasiak** [comment]
Consider passing `interfaces` to `Zeroconf` to customize the interfaces used – the default is just a default, it seems to be working all right for most cases but it may not work for you.

**Comment by jstasiak** [comment]
I *think* the condition can be removed actually, as the exceptions it's meant to prevent are caught and seem to be thrown away anyway, but it needs to be confirmed.
