### ISSUE TITLE
Refactor to be Sans-IO

### ISSUE THREAD

**Issue by om26er** [jstasiak/python-zeroconf#223]
I am investigating to write a multicast DNS implementation using asyncio. Doing that would most likely use much of the hardwork that has already been done in python-zeroconf. I believe with some refactoring this project code could be changed in such a way making room for separating the parsing/validation from IO. Opening ways for much better reusability of the code by other implementations of mDNS in Python.

I am willing to do that in smaller sets over the next couple of months if there is interest from the maintainers of this project.

More reading https://sans-io.readthedocs.io/

**Comment by om26er** [comment]
I did somewhat similar change in autobahn-java (websocket/wamp) a few months ago https://github.com/crossbario/autobahn-java/pull/445

**Comment by jstasiak** [comment]
Speaking for myself – this sounds great. I believe I watched the [Cory Benfield’s PyCon US 2016 talk on Building Protocol Libraries The Right Way](https://www.youtube.com/watch?v=7cC3_jGwl_U) some time ago and it made sense to me, it's always a shame to duplicate logic unnecessarily. I also see some other benefits of this possible change, as the parsing/validating/whatever else logic could be tested more easily without IO overhead, sleeping in tests etc.

Have you seen the [aiozeroconf project](https://github.com/frawau/aiozeroconf) which was forked from this one? I don't know what's its current state but I know it exists.

**Comment by om26er** [comment]
> Have you seen the [aiozeroconf project](https://github.com/frawau/aiozeroconf) which was forked from this one? I don't know what's its current state but I know it exists.

Didn't know it existed, but the project seems stagnant now. I will see if I can incorporate latest changes from python-zerconf master and fix conflicts over the weekend (less likely as I am traveling for FOSDEM).

PS: I am giving a talk at FOSDEM that uses python-zerconf as an "important" bit https://fosdem.org/2020/schedule/event/deskconnd_crossplatform_ipc/

**Comment by nmichaud** [comment]
A sansio approach would also make this usable from trio-based applications.

**Comment by bdraco** [comment]
@om26er The I/O has been better isolated in `upstream/master`.  Its not 100% since I did it in a way to minimize the breaking changes so existing use cases don't have to care about what changed under the hood.

Do you still have intrest in doing some additional cleanups?

**Comment by bdraco** [comment]
We implemented asyncio support.  Thats not exactly not the ask here, but this issue has gone stale so I'm going to close it now.
