### ISSUE TITLE
Different instances of ServiceInfo used for add and update service

### ISSUE THREAD

**Issue by PhilippSelenium** [jstasiak/python-zeroconf#231]
I have a device in my network that has two ports and announces mDNS on both ports for both IPv4 and IPv6 it is connected to two ports on my local PC.
Using avahi-browse I correctly get the IPv6 and IPv4 entries for both ports:
```
avahi-browse -t  _http._tcp
+   eth1 IPv6 MyDevice Web Interface               Web Site             local
+   eth1 IPv4 MyDevice Web Interface               Web Site             local
+   eth0 IPv6 MyDevice Web Interface               Web Site             local
+   eth0 IPv4 MyDevice Web Interface               Web Site             local
```

But when using Zeroconf with a listener as described in the README:
```
class MyListener:

    def add_service(self, zeroconf, type, name):
            info = zeroconf.get_service_info(type, name)

   def update_service(self, zeroconf, type, name):
           info = zeroconf.get_service_info(type, name)
``` 
The IP addresses get overwritten because every call to https://github.com/jstasiak/python-zeroconf/blob/1ca023fae4b586679446ceaf3e2e9955ea5bf180/zeroconf/__init__.py#L2184 creates a new instance of ServiceInfo. Shouldn't the Zeroconf instance keep track of the ServiceInfo instance and/or have an update_service_info method?

I can work around this problem by explicitly passing ip_eth0 and ip_eth1 to Zeroconf but it would be good to get all IPs in the ServiceInfo if the default of InterfaceChoice.All is set.

**Comment by jstasiak** [comment]
Hey, I'm not entirely clear on what the issue is – can you post a sample code with some logging/prints, its output and say what you expect to see instead?

**Comment by PhilippSelenium** [comment]
The sample code is the code used in the example from teh README.
To reproduce a local PC and a remote mDNS device with two ports each is needed.
As stated above avahi browse can correctly resolve this python-zeroconf cannot (2 service info entries instead of four).
The only workaround is to use it on specific ports only.

**Comment by PhilippSelenium** [comment]
I don't have this issue anymore with the newest release but I have no clue why.
