### ISSUE TITLE
On systems without IPv6 this module crashes out

### ISSUE THREAD

**Issue by pancho-villa** [jstasiak/python-zeroconf#234]
Hello,

I ran into this issue and I _think_ it may be the zeroconf module. I'm using Home Assistant on FreeBSD that does not have IPv6 support. It bombs out when I try to interrogate the network for devices. See my github issue [here](https://github.com/home-assistant/core/issues/32717). 

It looks like my system doesn't like this particular line:

https://github.com/jstasiak/python-zeroconf/blob/8e3adf8300a6f2b0bc0dcc4cde54d8890e0727e9/zeroconf/__init__.py#L88

Should I make a pull request with a try except block there for weirdo systems like mine? I'm not sure if that's the best course, it's just my first wild ass guess at a solution.

Cheers

**Comment by jstasiak** [comment]
What's the value of `socket.has_ipv6` on your system? Yeah, if you could send a pull request our way it'd be cool.

**Comment by chemelli74** [comment]
I had a similar issue: [Zeroconf: bad file descriptor](https://github.com/home-assistant/core/issues/37791)

Would be nice to check if ipv6 is enabled on that particular interface before trying to init the socket.
Something like: 

```
import ipaddress
ipaddress.ip_address(ip) in ipaddress.IPv6Network(network)
```

Simone

**Comment by m4rkusxxl** [comment]
I was able to cover the call in try-except and be fine.
Error message:
> _MDNS_ADDR6_BYTES = socket.inet_pton(socket.AF_INET6, _MDNS_ADDR6)
> OSError: can't use AF_INET6, IPv6 is disabled

solution:
`try:
    _MDNS_ADDR6_BYTES = socket.inet_pton(socket.AF_INET6, _MDNS_ADDR6)
except:
    pass`
