### ISSUE TITLE
Latest version has a performance regression

### ISSUE THREAD

**Issue by bdraco** [jstasiak/python-zeroconf#246]
I've seen ~30% uptick in my Home Assistant instance cpu usage since upgrading.  

The profile hits on `__init__.py:1501` and `__init__.py:1503`

It looks like a similar issue to what I fixed in 37fa0a0d59a5b5d09295a462bf911e82d2d770ed

@mattsaxon It looks like this changed recently. Any chance this can be optimized for a large cache?

**Comment by bdraco** [comment]
Everything is stable again after https://github.com/bdraco/python-zeroconf/commit/ccfe8509dfff1b7283a0b3a81780f65024936059 but this may cause a regression in @mattsaxon 's change

**Comment by jstasiak** [comment]
Can you attach a profile?

**Comment by bdraco** [comment]
I've been having trouble getting a full profile because the profiler can't sample fast enough without falling behind.  I'll try with a lower sampling rate.  That should be good enough

**Comment by bdraco** [comment]
I'll give it another shot in the morning when I've had some sleep.  I have to catch it before the cache gets too large and Home Assistant is unresponsive but there is enough in the cache that its not too slow to get a profile.

**Comment by mattsaxon** [comment]
In terms of a regression of my changes, if the unit tests pass, I’d say that you are good to go.

**Comment by bdraco** [comment]
I wasn't able to keep the `py-spy` running long enough to a full sample as it keep falling fruther and further behind `59.09s behind in sampling, results may be inaccurate. Try reducing the sampling rate.`

I was able to get a svg recording before things locked up on me

<img width="1248" alt="Screen Shot 2020-05-06 at 10 41 56 AM" src="https://user-images.githubusercontent.com/663432/81197726-3cffad00-8f86-11ea-902d-0997dfeafe3a.png">

**Comment by jstasiak** [comment]
Many thanks for the report and providing a solution (#247), the fix is released in 0.26.1 now.

**Comment by bdraco** [comment]
Thank you.  I'll get a PR done for Home Assistant shortly.
