### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by 0xFF1E071F** [jstasiak/python-zeroconf#253]
Hello can you plaese tag the new relase to github releases. I am making packages through downloading github releases.
Thank you

**Comment by emontnemery** [comment]
The releases are tagged, the list of releases is here: https://github.com/jstasiak/python-zeroconf/releases

**Comment by jstasiak** [comment]
Although this time I forgot to push the 0.26.2 tag after creating it locally, fixed now.

**Comment by 0xFF1E071F** [comment]
Thank you
