### ISSUE TITLE
Zeroconf.get_service_info seems broken in 0.26.0

### ISSUE THREAD

**Issue by emontnemery** [jstasiak/python-zeroconf#255]
Several Home Assistant users have reported that cast devices can't be discovered correctly after a recent upgrade which bumps zeroconf from 0.25.1 to 0.26.1: https://github.com/home-assistant/core/issues/35922

According to some testing, the problem appeared in 0.26.0, which adds jstasiak/python-zeroconf#239

It seems that the problem is that `Zeroconf.get_service_info` doesn't return anything useful in 0.26.0+, from the logs it seems that Zeroconf keeps sending queries but does not get or does not accept answers.

Debug logs here:
https://github.com/home-assistant/core/issues/35922#issuecomment-633261933

For context, this is the code in pychromecast which calls `Zeroconf.get_service_info`, look for the `add_service` and `service` prints in the logs:
```py
    def add_service(self, zconf, typ, name):
        """ Add a service to the collection. """
        service = None
        tries = 0
        _LOGGER.debug("add_service %s, %s", typ, name)
        while service is None and tries < 4:
            try:
                service = zconf.get_service_info(typ, name)
            except IOError:
                # If the zeroconf fails to receive the necessary data we abort
                # adding the service
                break
            tries += 1

        if not service:
            _LOGGER.debug("add_service failed to add %s, %s", typ, name)
            return
```

@mattsaxon, any idea?

**Comment by gjbadros** [comment]
I haven't looked at this hard, but the mdns-repeater process that is running under the HASS supervisor has crashed for me before, resulting in failed service discovery.  Is the setup where the problem occurs relying on mdns-repeater and is it still running?  (I had to docker restart that container.)

**Comment by hmmbob** [comment]
Yes. I run the mdns repeater on the host and can stop the container with the not-working 0.26.0 setup and start the container with 0.25.1 to get a working set-up back - without further touching (or reboot) of the host.

Logs indicate that mdns traffic is still being reflected as well.

**Comment by jstasiak** [comment]
@emontnemery Is this about `add_service` callback not being called at all, or it being called all the same but `get_service_info()` returns some garbage now? If it's the former I suspect this is the explanation: zeroconf receives multiple packets/responses for the cast devices before it's able to dispatch first service added callback, so it dispatches service updated callback (since it already knew about the device(s)).

**Comment by jstasiak** [comment]
How that I think about this it should be the case only if a record changes, and I don't think you expect this here.

**Comment by mattsaxon** [comment]
I've just run some local tests with zeroconf 26.1 and a chromecast and it seems to be working both from a python test harness and also my HA (0.110.1) recognises it fine, including after a restart of HA.

**Comment by hmmbob** [comment]
Are you using docker?

**Comment by mattsaxon** [comment]
No I'm not using Docker.

There's a lot of logs to go through there, can we first try to isolate this to if if it occurs when not using HA with a simple test harness? The reason I mention this is there seemed to be quite a lot of changes to the way zeroconf was being used in HA 0.110 from a quick scan of the release logs.

**Comment by hmmbob** [comment]
The Q about docker was because the thread seems to only have docker users reporting the issue - for now. 

To summarize what we did already:

HA 109.6 with zeroconf 25.1 (default): all works fine
HA 110.0 with zeroconf 26.0 (default): cast broken
HA 110.0 with zeroconf 25.1 (requires manual installation): cast works fine again

26.1 and 26.2 didn't solve the issue either btw 

"Cast broken" in this context means that not all devices seem to connect, or more specifically: any device after the first one.

**Comment by mattsaxon** [comment]
OK, thanks, that's a useful summary. Just reran my test harness, adding a second (mocked) chromecast device and this work fine too.

Can you enhance the logging in the code posted at the top of this thread, can you please catch all exceptions (rather than just IOError and log the exception in both cases so we can see what is occurring.

**Comment by hmmbob** [comment]
I'll try later today - but it will require some work inside the docker container so i'll be needing some time to set everything up. I'll report back though.

**Comment by mattsaxon** [comment]
One thing to consider is that I’ve realised that I’m also implicitly using docker for my HA as I’m using HassOS. My test harness is running on a Window machine however elsewhere on my network. Is it worth us trying to produce this outside of HA first as it will save you fiddling with your HA? Also if we can’t produce it outside of HA it will help us with the diagnosis. Your call obviously, I’ll support you whichever way you choose to go.

**Comment by emontnemery** [comment]
The key difference between the 0.25.1 and 0.26.1 logs is that `Zeroconf.get_service_info` returns None in 0.26.1.

Example from 0.25.1 log:
```
2020-05-24 16:37:39 DEBUG (zeroconf-ServiceBrowser__googlecast._tcp.local.) [pychromecast.discovery] add_service _googlecast._tcp.local., Chromecast-32e39183bc97abac51d77fce98a766a4-7._googlecast._tcp.local.
^--- This results in a call to `Zeroconf.get_service_info
2020-05-24 16:37:39 DEBUG (zeroconf-ServiceBrowser__googlecast._tcp.local.) [homeassistant.components.cast.discovery] Discovered chromecast ChromecastInfo(host='192.168.88.11', port=8009, service='Chromecast-32e39183bc97abac51d77fce98a766a4-7._googlecast._tcp.local.', uuid='32e39183-bc97-abac-51d7-7fce98a766a4', model_name='Chromecast', friendly_name='TV Slaapkamer')
^--- This means `Zeroconf.get_service_info returned a a service. Note in the log that no packages were sent by zeroconf to resolve the service
```

Example from 0.26.1 log:
```
2020-05-24 18:50:27 DEBUG (zeroconf-ServiceBrowser__googlecast._tcp.local.) [pychromecast.discovery] add_service _googlecast._tcp.local., Chromecast-32e39183bc97abac51d77fce98a766a4-7._googlecast._tcp.local.
^--- This results in a call to `Zeroconf.get_service_info
2020-05-24 18:50:27 DEBUG (zeroconf-ServiceBrowser__googlecast._tcp.local.) [zeroconf] Sending <DNSOutgoing:{multicast=True, flags=0, questions=[question[srv,in,Chromecast-32e39183bc97abac51d77fce98a766a4-7._googlecast._tcp.local.], question[txt,in,Chromecast-32e39183bc97abac51d77fce98a766a4-7._googlecast._tcp.local.], question[a,in,Chromecast-32e39183bc97abac51d77fce98a766a4-7._googlecast._tcp.local.], question[quada,in,Chromecast-32e39183bc97abac51d77fce98a766a4-7._googlecast._tcp.local.]], answers=[], authorities=[], additionals=[]}> (104 bytes) as b'\x00\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00-Chromecast-32e39183bc97abac51d77fce98a766a4-7\x0b_googlecast\x04_tcp\x05local\x00\x00!\x00\x01\xc0\x0c\x00\x10\x00\x01\xc0\x0c\x00\x01\x00\x01\xc0\x0c\x00\x1c\x00\x01'...
^--- Question from zeroconf
2020-05-24 18:50:27 DEBUG (zeroconf-Engine) [zeroconf] Received from '172.22.0.2':5353: b'\x00\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00-Chromecast-32e39183bc97abac51d77fce98a766a4-7\x0b_googlecast\x04_tcp\x05local\x00\x00!\x00\x01\xc0\x0c\x00\x10\x00\x01\xc0\x0c\x00\x01\x00\x01\xc0\x0c\x00\x1c\x00\x01' 
2020-05-24 18:50:27 DEBUG (zeroconf-Engine) [zeroconf] Received from '172.22.0.1':5353: b'\x00\x00\x84\x00\x00\x00\x00\x02\x00\x00\x00\x00-Chromecast-32e39183bc97abac51d77fce98a766a4-7\x0b_googlecast\x04_tcp\x05local\x00\x00\x10\x80\x01\x00\x00\x11\x94\x00\xac#id=32e39183bc97abac51d77fce98a766a4#cd=C69CA6478A7752218282F68F6D6520C6\x03rm=\x05ve=05\rmd=Chromecast\x12ic=/setup/icon.png\x10fn=TV Slaapkamer\tca=200709\x04st=0\x0fbs=FA8FCA9E2B99\x04nf=2\x03rs=\xc0\x0c\x00!\x80\x01\x00\x00\x00x\x00/\x00\x00\x00\x00\x1fI&32e39183-bc97-abac-51d7-7fce98a766a4-1\xc0K' 
2020-05-24 18:50:39 DEBUG (zeroconf-ServiceBrowser__googlecast._tcp.local.) [pychromecast.discovery] add_service failed to add _googlecast._tcp.local., Chromecast-32e39183bc97abac51d77fce98a766a4-7._googlecast._tcp.local.
^--- pychromecast gives upp after  `Zeroconf.get_service_info` returned `None` 4 times
```

Another key difference between the 0.25.1 and 0.26.1 logs is that `add_service` is called multiple times for the same cast device in case of 0.25.1, although with different suffixes for the name:
```
[pychromecast.discovery] add_service _googlecast._tcp.local., Chromecast-32e39183bc97abac51d77fce98a766a4-7._googlecast._tcp.local.
2020-05-24 16:37:54 DEBUG (zeroconf-ServiceBrowser__googlecast._tcp.local.) [pychromecast.discovery] add_service _googlecast._tcp.local., Chromecast-32e39183bc97abac51d77fce98a766a4-6._googlecast._tcp.local.
2020-05-24 16:37:54 DEBUG (zeroconf-ServiceBrowser__googlecast._tcp.local.) [pychromecast.discovery] add_service _googlecast._tcp.local., Chromecast-32e39183bc97abac51d77fce98a766a4-5._googlecast._tcp.local.
2020-05-24 16:38:06 DEBUG (zeroconf-ServiceBrowser__googlecast._tcp.local.) [pychromecast.discovery] add_service _googlecast._tcp.local., Chromecast-32e39183bc97abac51d77fce98a766a4-4._googlecast._tcp.local.
2020-05-24 16:38:42 DEBUG (zeroconf-ServiceBrowser__googlecast._tcp.local.) [pychromecast.discovery] add_service _googlecast._tcp.local., Chromecast-32e39183bc97abac51d77fce98a766a4-3._googlecast._tcp.local.
2020-05-24 16:38:54 DEBUG (zeroconf-ServiceBrowser__googlecast._tcp.local.) [pychromecast.discovery] add_service _googlecast._tcp.local., Chromecast-32e39183bc97abac51d77fce98a766a4-2._googlecast._tcp.local.```

note: `pychromecast` is relying only on `add_service`, `update_service` is not implemented.
@mattsaxon With your changes in #239, is it now necessary to also add `update_service`?

Maybe this is just a red herring though?

**Comment by mattsaxon** [comment]
It would be a good test to see what implanting update_service yields, however this would be a bug which we would rectify, the only requirement to implement update_service SHOULD be to get updates, such as if the IP address changes.

**Comment by emontnemery** [comment]
It's 7 services from one device. 

IIRC:
This is a fallback if the preffered name, without suffix, is already taken.
The Chromecast sends a question for its preferred name, and if receiving an answer, adds a suffix.

Due to the nature of mDNS, the name may be taken by the Chromecast itself before it rebooted or reconnected etc, but cached by another client.

If @hmmbob has been "messing around" shortly before logging, that may explain the multiple services, and also why they show up in one log but not another.

**Comment by emontnemery** [comment]
@hmmbob A bit crazy, but could you try patching pychromecast/discovery.py by adding this to `CastListener`:
```
    def update_service(self, zconf, typ, name):
        _LOGGER.debug("update_service %s, %s", typ, name)
        self.add_service(zconf, typ, name)
        _LOGGER.debug("update_service done for %s, %s", typ, name)
```

**Comment by mattsaxon** [comment]
Looks a good suggestion.

Given what you’ve said about the large number of suffixes, I wonder if the issue is down to a large Mdns packet being split and when the first packet comes in,  that there is not enough information to provide the data needed to service the get_service_info call. If this is the case, on a failure (ie receiving none), you could try waiting for, say 1 second and trying again. At the moment the code retries 4 times without a wait.

**Comment by hmmbob** [comment]
> @hmmbob A bit crazy, but could you try patching pychromecast/discovery.py by adding this to `CastListener`:
> 
> ```
>     def update_service(self, zconf, typ, name):
>         _LOGGER.debug("update_service %s, %s", typ, name)
>         self.add_service(zconf, typ, name)
>         _LOGGER.debug("update_service done for %s, %s", typ, name)
> ```

What testing/code changes do you want me to focus first on? I've just got limited time available tonight, but I do want to help you guys forward with debugging this....

**Comment by emontnemery** [comment]
@hmmbob My proposal is to:
Test both zeroconf 0.25.1 and 0.26.1 with the following changes
- Patch zeroconf to enable debug log: https://github.com/home-assistant/core/issues/35922#issuecomment-632908646
- Patch zeroconf to improve debug log: #254
- Patch patching pychromecast/discovery.py by adding this to CastListener:
```diff
+    def update_service(self, zconf, typ, name):
+        _LOGGER.debug("update_service %s, %s", typ, name)
+        self.add_service(zconf, typ, name)
+        _LOGGER.debug("update_service done for %s, %s", typ, name)
+
     def add_service(self, zconf, typ, name):
         """ Add a service to the collection. """
+        import time
         service = None
         tries = 0
         _LOGGER.debug("add_service %s, %s", typ, name)
         while service is None and tries < 4:
             try:
                 service = zconf.get_service_info(typ, name)
                 _LOGGER.debug("service: %s", service)
             except IOError:
                 # If the zeroconf fails to receive the necessary data we abort
                 # adding the service
                 break
             tries += 1
+            if service is None:
+                time.sleep(1)
```

@mattsaxon Does this seem reasonable? Is the `sleep()` in the right place?

**Comment by jstasiak** [comment]
I'll let @mattsaxon speak for himself, but to me it looks like a reasonable direction (with the small exception of patching `zeroconf` to enable debug logs, see https://github.com/home-assistant/core/issues/35922#issuecomment-633630112).

**Comment by hmmbob** [comment]
> ```diff
> +    def update_service(self, zconf, typ, name):
> +        _LOGGER.debug("update_service %s, %s", typ, name)
> +        self.add_service(zconf, typ, name)
> +        _LOGGER.debug("update_service done for %s, %s", typ, name)
> ```

First run is done. I started a brand new HA 110.0 container (to make sure previous debugging did not interfere). I observed none of the cast devices to show. Within the container, I patched the files as quoted above (i seem to get handy with `vi` while doing this, lol) and restarted home assistant. I observed none of the devices to show upon startup, but suddenly at 18:32-ish most of the devices showed up. I am still missing one chromecast device (LS-SH8 soundbar) and an AndroidTV (but that is quite regular if that one isn't turned on - which it isnt).

**Comment by hmmbob** [comment]
And the second run is done too. I again started a brand new 110.0 container and observed all cast devices showing as unavailable. I installed zeroconf 25.1, patched all files as requested and restarted home assistant. I observed all cast devices to be online immediately when the HA frontend is available.

Logs: [110-25.1-patched.log](https://www.hmmbob.nl/110-25.1-patched.log)

**Comment by emontnemery** [comment]
Nice!

I think adding `update_service` is why the devices show up around 18:32:
```
2020-05-25 18:32:21 DEBUG (zeroconf-ServiceBrowser__googlecast._tcp.local.) [pychromecast.discovery] update_service _googlecast._tcp.local., Google-Home-d4063db0253e246c9d66d8f7fda77a6a._googlecast._tcp.local.
2020-05-25 18:32:21 DEBUG (zeroconf-ServiceBrowser__googlecast._tcp.local.) [pychromecast.discovery] add_service _googlecast._tcp.local., Google-Home-d4063db0253e246c9d66d8f7fda77a6a._googlecast._tcp.local.
```

**Comment by emontnemery** [comment]
#239 adds the lock `_handlers_lock`:
https://github.com/jstasiak/python-zeroconf/blob/552a030eb592a0c07feaa7a01ece1464da4b1d0b/zeroconf/__init__.py#L2209

Which is used in the engine thread:
https://github.com/jstasiak/python-zeroconf/blob/552a030eb592a0c07feaa7a01ece1464da4b1d0b/zeroconf/__init__.py#L2484-L2489

And also by the service browser when issuing the state change callbacks:
https://github.com/jstasiak/python-zeroconf/blob/552a030eb592a0c07feaa7a01ece1464da4b1d0b/zeroconf/__init__.py#L1541-L1546

Both pychromecast and Home Assistant calls `Zeroconf.get_service_info` from the service callbacks which means the lock may be held for several seconds. Could this be the root cause of this issue?

**Comment by mattsaxon** [comment]
I haven’t considered what you’ve written above yet, but let me explain why I added the lock. The intention was to deal with the situation of calling add_service and then uofate_service day in short succession. The expectations was that adding it would allow the add_serivce to have all the information rather than called add_service early and then calling update_service. Pretty much trying to avoid the problem we may be facing here .

**Comment by emontnemery** [comment]
OK, so the intention is to prevent the service browsers from rushing away and call `add_service` too early while looping over `for record in msg.answers:`?

Maybe the lock can remain, but make a list `handlers_to_really_really_call` which can be looped over without holding the lock:

```diff
             if len(self._handlers_to_call) > 0 and not self.zc.done:
+                handlers_to_really_really_call = []
                 with self.zc._handlers_lock:
                     handler = self._handlers_to_call.popitem(False)
+                    handlers_to_really_really_call.append(handler)
+                for handler in handlers_to_really_really_call:
                     self._service_state_changed.fire(
                         zeroconf=self.zc, service_type=self.type, name=handler[0], state_change=handler[1]
                     )
```

**Comment by jstasiak** [comment]
I think this could be just deindenting the `self._service_state_changed.fire()` lines?

**Comment by emontnemery** [comment]
Yes, that's right, not sure what I was thinking @_@

**Comment by emontnemery** [comment]
Maybe another round of test, test with zeroconf 0.26.1 and the below changes.
@jstasiak, @hmmbob does it seem reasonable?

Changes:
- Patch zeroconf to enable debug log: https://github.com/home-assistant/core/issues/35922#issuecomment-632908646
- Patch zeroconf to improve debug log of incoming data: #254
- Patch zeroconf to not starve the engine thread:
```diff
             if len(self._handlers_to_call) > 0 and not self.zc.done:
                 with self.zc._handlers_lock:
                     handler = self._handlers_to_call.popitem(False)
-                    self._service_state_changed.fire(
-                        zeroconf=self.zc, service_type=self.type, name=handler[0], state_change=handler[1]
-                    )
+                self._service_state_changed.fire(
+                    zeroconf=self.zc, service_type=self.type, name=handler[0], state_change=handler[1]
+                )
```
- Patch pychromecast/discovery.py by adding this to CastListener:
```diff
+    def update_service(self, zconf, typ, name):
+        _LOGGER.debug("update_service %s, %s", typ, name)
+        self.add_service(zconf, typ, name)
+        _LOGGER.debug("update_service done for %s, %s", typ, name)
+
     def add_service(self, zconf, typ, name):
         """ Add a service to the collection. """
+        import time
         service = None
         tries = 0
         _LOGGER.debug("add_service %s, %s", typ, name)
         while service is None and tries < 4:
             try:
                 service = zconf.get_service_info(typ, name)
                 _LOGGER.debug("service: %s", service)
             except IOError:
                 # If the zeroconf fails to receive the necessary data we abort
                 # adding the service
                 break
             tries += 1
+            if service is None:
+                time.sleep(1)
```

**Comment by hmmbob** [comment]
I'll give it a run tomorrow!

**Comment by jstasiak** [comment]
@emontnemery Yes, +1 from me, although late, as @hmmbob was faster with actual testing. :)

**Comment by hmmbob** [comment]
But now I wonder why _I_ ran into this, with just a few others - but not the other thousands of HA users.....

**Comment by jstasiak** [comment]
Is the percentage of HA users who upgraded to the latest HA and use pychromecast/zeroconf known (not the precise figure, naturally, just an approximation)?

**Comment by emontnemery** [comment]
Based on the number of comments in https://github.com/home-assistant/core/issues/35922, i don't think the percentage is too high. A few users also complain in the forums.

@hmmbob is running a non recommended setup where the cast devices and home assistant are on different networks, with Avahi in reflector mode helping to bridge, that seems to be the common factor.

Maybe it would be worth digging a bit deeper in the logs from @hmmbob to understand why the deadlock / starve was triggered in this case. Maybe Avahi does some filtering of mDNS packets which somehow changes the timing cuasing `Zeroconf.get_service_info` to deadlock?
