### ISSUE TITLE
Provide more examples 

### ISSUE THREAD

**Issue by ThangaAyyanar** [jstasiak/python-zeroconf#278]
- Example to recieve and send data.
As a beginner to bonjour protocol stuff, i find it bit difficult to get started with this.

**Comment by ThangaAyyanar** [comment]
I can able to create a service but don't know how to receive data from it.

This is the software that i am trying to receive data from 
https://github.com/yagiz/Bagel/blob/master/iOS/Source/BagelBrowser.m

**Comment by jstasiak** [comment]
This library provides service discovery, not the means to actually talk to services after they're discovered. Do you have an issue (or need help) with the discovery specifically? Some piece of code that you have and that you have a problem with would be useful here to see what's going on.

**Comment by ThangaAyyanar** [comment]
Thanks for explanation, I can able to identify the service. I will explore more on my requirements.
