### ISSUE TITLE
Remove obsolete RuntimeError

### ISSUE THREAD

**Issue by PhilippSelenium** [jstasiak/python-zeroconf#279]
This RuntimeError https://github.com/jstasiak/python-zeroconf/blob/master/zeroconf/__init__.py#L2037
is still raised despite the MR https://github.com/pydron/ifaddr/pull/21 referenced in the comment is merged.
Either this comment is stale or the RuntimeError can be removed?

**Comment by jstasiak** [comment]
It is stale, someone needs to patch the code to use the new `Adapter.index` attribute from `ifaddr`, I haven't had time to do this.
