### ISSUE TITLE
Publish available services?

### ISSUE THREAD

**Issue by ekw** [jstasiak/python-zeroconf#289]
Can this module be used to publish available services, not just find/browse them?  I want to do the equivalent of avahi-publish-service from Windows OS, but can't find anything that allows me to do so.  There's a lot on discovering services via zeroconf on Windows, but not publishing services.  Thanks.

**Comment by jstasiak** [comment]
It can, see https://github.com/jstasiak/python-zeroconf/blob/master/examples/registration.py for an example.

**Comment by ekw** [comment]
Thank you.  And this is off-topic, but would you happen to know of a utility/application that accomplishes this also?  Again, something that does avahi-publish-service, but via an application/service, not a python script.  This is not a criticism of your module, just want to see if there's something more conventional.

**Comment by jstasiak** [comment]
I'm not entirely sure what the distinction between application/service and a Python script is in this context so I can't really point to anything.

**Comment by ekw** [comment]
I guess I mean an application that installs and is an executable, vs. calling python script.

Like for a web server, there's Apache and nginx, vs. using "python -m http.server 8000" (https://docs.python.org/3/library/http.server.html).

**Comment by emontnemery** [comment]
This is what you want: https://linux.die.net/man/1/avahi-publish-service

**Comment by ekw** [comment]
Yes, I'm looking for exactly that, but for Windows OS (see my OP).

**Comment by emontnemery** [comment]
Oops, sorry about that!

**Comment by jstasiak** [comment]
I had it in mind to create something like this as part of this package but never found time and motivation to actually follow through with it. Sadly I know no alternatives to `avahi-publish-service`.

**Comment by ekw** [comment]
OK, thanks!
