### ISSUE TITLE
Wrong argument list in call to ServiceBrowser constructor in Zeroconf.add_service_listener method

### ISSUE THREAD

**Issue by abadona** [jstasiak/python-zeroconf#291]
The ServiceBrowser constructor is called with 3 positional arguments: (self, type_, listener), while the ServiceBrowser__init__ expects the 'handlers' list as a third positional argument. This is a critical bug, use of add_service_listener is not possible due to it.

**Comment by jstasiak** [comment]
Please provide the Python version you're running, the python-zeroconf version, the code to reproduce and the full error with a stack trace.

**Comment by abadona** [comment]
In [head] of origin/master branch this problem is fixed. The code of ServiceBrowser.__init__ handles the listener passed as third positional argument properly. (The problem had manifested on Ubuntu 18.04 with the earlier version from Canonical repository, and disappeared after "apt upgrade". Unfortunately, I can not trace back the version in the repo due to unrelated technical issue. However, this seems to be not necessary as the current code works correctly.)
