### ISSUE TITLE
TestServiceBrowserMultipleTypes test regressed with 0.28.1

### ISSUE THREAD

**Issue by nullr0ute** [jstasiak/python-zeroconf#295]
The TestServiceBrowserMultipleTypes test now fails with the 0.28.1 release:

<pre>
=================================== FAILURES ===================================
______________ TestServiceBrowserMultipleTypes.test_update_record ______________
[gw2] linux -- Python 3.8.5 /usr/bin/python3
self = <zeroconf.test.TestServiceBrowserMultipleTypes testMethod=test_update_record>
    def test_update_record(self):
    
        service_names = ['name2._type2._tcp.local.', 'name._type._tcp.local.', 'name._type._udp.local']
        service_types = ['_type2._tcp.local.', '_type._tcp.local.', '_type._udp.local.']
    
        service_added_count = 0
        service_removed_count = 0
        service_add_event = Event()
        service_removed_event = Event()
    
        class MyServiceListener(r.ServiceListener):
            def add_service(self, zc, type_, name) -> None:
                nonlocal service_added_count
                service_added_count += 1
                if service_added_count == 3:
                    service_add_event.set()
    
            def remove_service(self, zc, type_, name) -> None:
                nonlocal service_removed_count
                service_removed_count += 1
                if service_removed_count == 3:
                    service_removed_event.set()
    
        def mock_incoming_msg(
            service_state_change: r.ServiceStateChange, service_type: str, service_name: str, ttl: int
        ) -> r.DNSIncoming:
            generated = r.DNSOutgoing(r._FLAGS_QR_RESPONSE)
            generated.add_answer_at_time(
                r.DNSPointer(service_type, r._TYPE_PTR, r._CLASS_IN, ttl, service_name), 0
            )
            return r.DNSIncoming(generated.packet())
    
        zeroconf = r.Zeroconf(interfaces=['127.0.0.1'])
        service_browser = r.ServiceBrowser(zeroconf, service_types, listener=MyServiceListener())
    
        try:
            wait_time = 3
    
            # all three services added
            zeroconf.handle_response(
                mock_incoming_msg(r.ServiceStateChange.Added, service_types[0], service_names[0], 120)
            )
            zeroconf.handle_response(
                mock_incoming_msg(r.ServiceStateChange.Added, service_types[1], service_names[1], 120)
            )
            zeroconf.handle_response(
                mock_incoming_msg(r.ServiceStateChange.Added, service_types[2], service_names[2], 120)
            )
    
            called_with_refresh_time_check = False
    
            def _mock_get_expiration_time(self, percent):
                nonlocal called_with_refresh_time_check
                if percent == _EXPIRE_REFRESH_TIME_PERCENT:
                    called_with_refresh_time_check = True
                    return 0
                return self.created + (percent * self.ttl * 10)
    
            # Set an expire time that will force a refresh
>           with unittest.mock.patch("zeroconf.DNSRecord.get_expiration_time", new=_mock_get_expiration_time):
E           AttributeError: module 'unittest' has no attribute 'mock'
zeroconf/test.py:1308: AttributeError
------------------------------ Captured log call -------------------------------
DEBUG    zeroconf:__init__.py:2116 Creating new socket with port 5353, ip_version IPVersion.V4Only, apple_p2p False and bind_addr ('',)
DEBUG    zeroconf:__init__.py:2175 Created socket <socket.socket fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 5353)>
DEBUG    zeroconf:__init__.py:2189 Adding '127.0.0.1' (socket 10) to multicast group
DEBUG    zeroconf:__init__.py:2116 Creating new socket with port 5353, ip_version IPVersion.V4Only, apple_p2p False and bind_addr ('127.0.0.1',)
DEBUG    zeroconf:__init__.py:2175 Created socket <socket.socket fd=12, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('127.0.0.1', 5353)>
DEBUG    zeroconf:__init__.py:2225 Configuring socket <socket.socket fd=12, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('127.0.0.1', 5353)> with multicast interface 127.0.0.1
DEBUG    zeroconf:__init__.py:2330 Listen socket <socket.socket fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 5353)>, respond sockets [<socket.socket fd=12, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('127.0.0.1', 5353)>]
DEBUG    zeroconf:__init__.py:1375 Received from '127.0.0.1':5353 (socket 10): <DNSIncoming:{id=0, flags=33792, n_q=0, n_ans=2, n_auth=0, n_add=6, questions=[], answers=[record[ptr,in,_my-service._tcp.local.]=4500/4499,a wonderful service-301._my-service._tcp.local., record[ptr,in,_my-service._tcp.local.]=4500/4499,a wonderful service-301._my-service._tcp.local., record[srv,in-unique,a wonderful service-301._my-service._tcp.local.]=120/119,ash-2.local.:80, record[txt,in-unique,a wonderful service-301._my-service._tcp.local.]=4500/4499,b'\x0epath=/'..., record[a,in-unique,ash-2.local.]=120/119,10.0.1.2, record[srv,in-unique,a wonderful service-301._my-service._tcp.local.]=120/119,ash-2.local.:80, record[txt,in-unique,a wonderful service-301._my-service._tcp.local.]=4500/4499,b'\x0epath=/'..., record[a,in-unique,ash-2.local.]=120/119,10.0.1.2]}> (218 bytes) as [b'\x00\x00\x84\x00\x00\x00\x00\x02\x00\x00\x00\x06\x0b_my-service\x04_tcp\x05local\x00\x00\x0c\x00\x01\x00\x00\x11\x94\x00\x1a\x17a wonderful service-301\xc0\x0c\xc0\x0c\x00\x0c\x00\x01\x00\x00\x11\x94\x00\x02\xc0.\xc0.\x00!\x80\x01\x00\x00\x00x\x00\x0e\x00\x00\x00\x00\x00P\x05ash-2\xc0\x1d\xc0.\x00\x10\x80\x01\x00\x00\x11\x94\x00\x0f\x0epath=/~paulsm/\xc0h\x00\x01\x80\x01\x00\x00\x00x\x00\x04\n\x00\x01\x02\xc0.\x00!\x80\x01\x00\x00\x00x\x00\x08\x00\x00\x00\x00\x00P\xc0h\xc0.\x00\x10\x80\x01\x00\x00\x11\x94\x00\x0f\x0epath=/~paulsm/\xc0h\x00\x01\x80\x01\x00\x00\x00x\x00\x04\n\x00\x01\x02']
DEBUG    zeroconf:__init__.py:1158 offsets = 0, 0, 0
DEBUG    zeroconf:__init__.py:1159 lengths = 0, 0, 0
DEBUG    zeroconf:__init__.py:1195 now offsets = 0, 0, 0
DEBUG    zeroconf:__init__.py:2823 Sending (35 bytes #1) <DNSOutgoing:{multicast=True, flags=0, questions=[question[ptr,in,_type2._tcp.local.]], answers=[], authorities=[], additionals=[]}> as b'\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x06_type2\x04_tcp\x05local\x00\x00\x0c\x00\x01'...
DEBUG    zeroconf:__init__.py:1375 Received from '127.0.0.1':5353 (socket 10): <DNSIncoming:{id=0, flags=0, n_q=1, n_ans=0, n_auth=0, n_add=0, questions=[question[ptr,in,_type2._tcp.local.]], answers=[]}> (35 bytes) as [b'\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x06_type2\x04_tcp\x05local\x00\x00\x0c\x00\x01']
DEBUG    zeroconf:__init__.py:1158 offsets = 0, 0, 0
DEBUG    zeroconf:__init__.py:1159 lengths = 0, 0, 0
DEBUG    zeroconf:__init__.py:1195 now offsets = 0, 0, 0
DEBUG    zeroconf:__init__.py:2823 Sending (34 bytes #1) <DNSOutgoing:{multicast=True, flags=0, questions=[question[ptr,in,_type._udp.local.]], answers=[], authorities=[], additionals=[]}> as b'\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x05_type\x04_udp\x05local\x00\x00\x0c\x00\x01'...
DEBUG    zeroconf:__init__.py:1158 offsets = 0, 0, 0
DEBUG    zeroconf:__init__.py:1159 lengths = 0, 0, 0
DEBUG    zeroconf:__init__.py:1195 now offsets = 0, 0, 0
DEBUG    zeroconf:__init__.py:2823 Sending (34 bytes #1) <DNSOutgoing:{multicast=True, flags=0, questions=[question[ptr,in,_type._tcp.local.]], answers=[], authorities=[], additionals=[]}> as b'\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x05_type\x04_tcp\x05local\x00\x00\x0c\x00\x01'...
DEBUG    zeroconf:__init__.py:1375 Received from '127.0.0.1':5353 (socket 10): <DNSIncoming:{id=0, flags=33792, n_q=0, n_ans=2, n_auth=0, n_add=6, questions=[], answers=[record[ptr,in,_my-service._tcp.local.]=4500/4499,a wonderful service-301._my-service._tcp.local., record[ptr,in,_my-service._tcp.local.]=4500/4499,a wonderful service-301._my-service._tcp.local., record[srv,in-unique,a wonderful service-301._my-service._tcp.local.]=120/119,ash-2.local.:80, record[txt,in-unique,a wonderful service-301._my-service._tcp.local.]=4500/4499,b'\x0epath=/'..., record[a,in-unique,ash-2.local.]=120/119,10.0.1.2, record[srv,in-unique,a wonderful service-301._my-service._tcp.local.]=120/119,ash-2.local.:80, record[txt,in-unique,a wonderful service-301._my-service._tcp.local.]=4500/4499,b'\x0epath=/'..., record[a,in-unique,ash-2.local.]=120/119,10.0.1.2]}> (218 bytes) as [b'\x00\x00\x84\x00\x00\x00\x00\x02\x00\x00\x00\x06\x0b_my-service\x04_tcp\x05local\x00\x00\x0c\x00\x01\x00\x00\x11\x94\x00\x1a\x17a wonderful service-301\xc0\x0c\xc0\x0c\x00\x0c\x00\x01\x00\x00\x11\x94\x00\x02\xc0.\xc0.\x00!\x80\x01\x00\x00\x00x\x00\x0e\x00\x00\x00\x00\x00P\x05ash-2\xc0\x1d\xc0.\x00\x10\x80\x01\x00\x00\x11\x94\x00\x0f\x0epath=/~paulsm/\xc0h\x00\x01\x80\x01\x00\x00\x00x\x00\x04\n\x00\x01\x02\xc0.\x00!\x80\x01\x00\x00\x00x\x00\x08\x00\x00\x00\x00\x00P\xc0h\xc0.\x00\x10\x80\x01\x00\x00\x11\x94\x00\x0f\x0epath=/~paulsm/\xc0h\x00\x01\x80\x01\x00\x00\x00x\x00\x04\n\x00\x01\x02']
DEBUG    zeroconf:__init__.py:1375 Received from '127.0.0.1':5353 (socket 10): <DNSIncoming:{id=0, flags=0, n_q=1, n_ans=0, n_auth=0, n_add=0, questions=[question[ptr,in,_type._udp.local.]], answers=[]}> (34 bytes) as [b'\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x05_type\x04_udp\x05local\x00\x00\x0c\x00\x01']
DEBUG    zeroconf:__init__.py:1375 Received from '127.0.0.1':5353 (socket 10): <DNSIncoming:{id=0, flags=0, n_q=1, n_ans=0, n_auth=0, n_add=0, questions=[question[ptr,in,_type._tcp.local.]], answers=[]}> (34 bytes) as [b'\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x05_type\x04_tcp\x05local\x00\x00\x0c\x00\x01']
DEBUG    zeroconf:__init__.py:1158 offsets = 0, 0, 0
DEBUG    zeroconf:__init__.py:1159 lengths = 1, 0, 0
DEBUG    zeroconf:__init__.py:1195 now offsets = 1, 0, 0
DEBUG    zeroconf:__init__.py:1158 offsets = 0, 0, 0
DEBUG    zeroconf:__init__.py:1159 lengths = 1, 0, 0
DEBUG    zeroconf:__init__.py:1195 now offsets = 1, 0, 0
DEBUG    zeroconf:__init__.py:1158 offsets = 0, 0, 0
DEBUG    zeroconf:__init__.py:1159 lengths = 1, 0, 0
DEBUG    zeroconf:__init__.py:1195 now offsets = 1, 0, 0
DEBUG    zeroconf:__init__.py:1375 Received from '127.0.0.1':5353 (socket 10): <DNSIncoming:{id=0, flags=33792, n_q=0, n_ans=2, n_auth=0, n_add=6, questions=[], answers=[record[ptr,in,_my-service._tcp.local.]=4500/4499,a wonderful service-301._my-service._tcp.local., record[ptr,in,_my-service._tcp.local.]=4500/4499,a wonderful service-301._my-service._tcp.local., record[srv,in-unique,a wonderful service-301._my-service._tcp.local.]=120/119,ash-2.local.:80, record[txt,in-unique,a wonderful service-301._my-service._tcp.local.]=4500/4499,b'\x0epath=/'..., record[a,in-unique,ash-2.local.]=120/119,10.0.1.2, record[srv,in-unique,a wonderful service-301._my-service._tcp.local.]=120/119,ash-2.local.:80, record[txt,in-unique,a wonderful service-301._my-service._tcp.local.]=4500/4499,b'\x0epath=/'..., record[a,in-unique,ash-2.local.]=120/119,10.0.1.2]}> (218 bytes) as [b'\x00\x00\x84\x00\x00\x00\x00\x02\x00\x00\x00\x06\x0b_my-service\x04_tcp\x05local\x00\x00\x0c\x00\x01\x00\x00\x11\x94\x00\x1a\x17a wonderful service-301\xc0\x0c\xc0\x0c\x00\x0c\x00\x01\x00\x00\x11\x94\x00\x02\xc0.\xc0.\x00!\x80\x01\x00\x00\x00x\x00\x0e\x00\x00\x00\x00\x00P\x05ash-2\xc0\x1d\xc0.\x00\x10\x80\x01\x00\x00\x11\x94\x00\x0f\x0epath=/~paulsm/\xc0h\x00\x01\x80\x01\x00\x00\x00x\x00\x04\n\x00\x01\x02\xc0.\x00!\x80\x01\x00\x00\x00x\x00\x08\x00\x00\x00\x00\x00P\xc0h\xc0.\x00\x10\x80\x01\x00\x00\x11\x94\x00\x0f\x0epath=/~paulsm/\xc0h\x00\x01\x80\x01\x00\x00\x00x\x00\x04\n\x00\x01\x02']
===================== 1 failed, 47 passed in 15.89 seconds =====================
</pre>

**Comment by karelyatin** [comment]
Test test_reaper_with_dict_change_during_iteration added in 0.28.4 also fails with same error

**Comment by jstasiak** [comment]
The tests are running fine, we have CI to verify this: https://travis-ci.org/github/jstasiak/python-zeroconf/builds/718754859

**Comment by nullr0ute** [comment]
What version of python? This is with 3.9

**Comment by jstasiak** [comment]
@nullr0ute Well, all the supported Python versions up to 3.8 (patch numbers vary). It's not possible to verify this report without details like the OS and the exact Python version you're using. Can you be more precise than 3.9? In the original report I see Python 3.8.5, not 3.9 (but it works for me on precisely that version on Mac OS, so that's weird anyway).

**Comment by jstasiak** [comment]
@nullr0ute Ah, sorry, I see `Linux` in your report. I can't reproduce this.

@karelyatin Please provide details about your setup, can't reproduce or verify without this.

**Comment by jstasiak** [comment]
The tests pass on Python 3.9 as well (https://github.com/jstasiak/python-zeroconf/pull/300), not sure what exact version of 3.9 is this though.

**Comment by nullr0ute** [comment]
Fedora 33 with python 3.9 rc1

**Comment by jstasiak** [comment]
Thanks. Hmm, interesting. Does it help if you add `import unittest.mock` somewhere in the import section in `zeroconf/test.py`? I guess we should've been importing it that way in the first place.

**Comment by jstasiak** [comment]
0.28.5 resolves this if I understand correctly.

**Comment by nullr0ute** [comment]
Yes, looks good to me!

**Comment by karelyatin** [comment]
Yes workes fine tested https://kojipkgs.fedoraproject.org//work/tasks/7113/51217113/build.log

**Comment by jstasiak** [comment]
Thanks for the feedback. :)
