### ISSUE TITLE
Redesign listener system

### ISSUE THREAD

**Issue by jstasiak** [jstasiak/python-zeroconf#3]

**Comment by jstasiak** [comment]
So https://github.com/jstasiak/python-zeroconf/commit/d162e54c6aad175505028aa7beb8a1a0cb7a231d goes in the direction I intended the interface to go but I think I'll restore the old interface at least until the next release but mark it as deprecated.

**Comment by lexruee** [comment]
@jstasiak Hi! I'm curious. What's the reason to change the listener system?

**Comment by jstasiak** [comment]
Hey @lexruee my primary reason it's class based to you need to create a class to listen to events or use some hackery to pass your handler methods in some other way - I think we can do better. I'm looking for some ideas other than what I implemented in d162e54 because I'm not entirely happy with it though.

**Comment by lexruee** [comment]
@jstasiak The old implementation uses the observer pattern applied on the ServiceBrowser. But I can understand why one could argue not use it. [Link](http://stackoverflow.com/questions/11619680/why-should-the-observer-pattern-be-deprecated)

Do you have in mind to implement something like that:

```python
browser = ServiceBrowser(zeroconf, "_http._tcp.local.")
browser.on_event('add_service', callback)
browser.on_event('remove_service', callback)
```

Anyways, I'm new to python, so I don't know the pythonic way :-).

**Comment by jstasiak** [comment]
Right now the secondary, experimental, listener system looks like this:

```python

def handler(zeroconf, service_type, name, state_change):
    pass

# then you can do this
browser = ServiceBrowser(zeroconf, '_http._tcp.local.', handlers=[handler])

# or that

browser = ServiceBrowser(zeroconf, '_http._tcp.local.')
browser.service_state_changed.register_handler(handler)
```

It doesn't require you to create a class to have a handler but I'm not sure how Pythonic it is. As another alternative I'm thinking about is to expose an interface returning iterators, such iterators would yield events discovered by the ``ServiceBrowser``:

```python
browser = ServiceBrowser(zeroconf, '_http._tcp.local.')
events = browser.get_iterator()
for e in events:
    print(e.state_change, e.name, ...)
```

**Comment by lexruee** [comment]
In my opinion it's fine to have a generic service state handler. 

But I would also provide a shortcut to register specific event handlers like 'add_service' or 'remove_service' which are called if such an event occurs. In that case you could avoid to write a generic event handler where you need if-elsif-else statements to distinguish between events.

And instead I  of exposing the 'service_state_changed.' property to register new handlers I would use a method like 'register_listener'. 

However, that's just my opinion :-) (based on java / ruby experience)

**Comment by jstasiak** [comment]
@lexruee Thanks for the notes, I'll definitely keep this in mind

**Comment by jstasiak** [comment]
Closing as I have no plan to do this at the moment.
