### ISSUE TITLE
How to receive data from bonjour-demo-osx-to-ios？

### ISSUE THREAD

**Issue by taichi-suzuki-pckg** [jstasiak/python-zeroconf#301]
I used [bonjour-demo-osx-to-ios](https://github.com/jameszaghini/bonjour-demo-osx-to-ios
) to send the data. Then I tried Python-Zeroconf to receive the data. I was able to receive the terminal information of the phone such as the IP address and port, but I could not receive the data sent from the phone.

Is there a way to receive the data sent using bonjourClient.send (data) in [ViewController.swift](https://github.com/jameszaghini/bonjour-demo-osx-to-ios/blob/master/bonjour-demo-ios/ViewController.swift) of this project in Python-Zeroconf?

I wrote the following code but only received the iPhone device name.
```
from zeroconf import ServiceBrowser, Zeroconf

class MyListener:
	def __init__(self):
		self.infoName = None
		
	def remove_service(self, zeroconf, type, name):
		print("Service %s removed" % (name,))

	def add_service(self, zeroconf, type, name):
		info = zeroconf.get_service_info(type, name)
		self.infoName = info.name

zeroconf = Zeroconf()
listener = MyListener()
while True:
	browser = ServiceBrowser(zeroconf, "_probonjore._tcp.local.", listener)
	print(listener.infoName)

try:
	input("Press enter to exit...\n\n")
finally:
	zeroconf.close()
```

**Comment by jstasiak** [comment]
OK, two things here:

* You only need and want to construct `ServiceBrowser` once and keep it alive – a background thread will call your listener when new information arrives (https://github.com/jstasiak/python-zeroconf/blob/master/examples/browser.py for an example, although it uses a different listener/handler interface, the library supports two such interfaces). If you construct `ServiceBrowser` instances in a loop like this you'll waste a lot of CPU time in the best case and won't actually discover any services in the worst case.
* I'm not clear on what "sending data" in `bonjour-demo-osx-to-ios` context is, but this library won't help you. The library only provides service advertisement/discovery. Once you know of a remote service and you want to communicate with it it's out of scope of this project ("sending data" may be as simple as using UDP to send/receive plain-text messages, I'd try that if you're experimenting with this).

**Comment by taichi-suzuki-pckg** [comment]
Thank you for the reply. bonjourClient.send (data) is udp and has nothing to do with bonjour, right? Based on your answer, I will use your code. Thank you.

**Comment by jstasiak** [comment]
No problem. :) Yeah, from what I see:

* On the iOS side it [opens a TCP socket and advertises a service with the socket's port number over Bonjour](https://github.com/jameszaghini/bonjour-demo-osx-to-ios/blob/c7eb7c3b99e09573c2c19d8d19ea3a1d69b1803c/bonjour-demo-ios/BonjourClient.swift#L34):
  ```objc
    func startBroadCasting() {
        socket = GCDAsyncSocket(delegate: self, delegateQueue: DispatchQueue.main)
        var error: NSError?
        do {
            try socket.accept(onPort: 0)
            service = NetService(domain: "local.", type: "_probonjore._tcp.", name: UIDevice.current.name, port: Int32(socket.localPort))
            service.delegate = self
            service.publish()
(...)
```
* `BonjourClient.send` [writes a data prefixed with a header to the socket](https://github.com/jameszaghini/bonjour-demo-osx-to-ios/blob/c7eb7c3b99e09573c2c19d8d19ea3a1d69b1803c/bonjour-demo-ios/BonjourClient.swift#L58):
  ```objc
    func send(_ data: Data) {
        var header = data.count
        let headerData = Data(bytes: &header, count: MemoryLayout<UInt>.size)
        socket.write(headerData, withTimeout: -1.0, tag: PacketTag.header.rawValue)
        socket.write(data, withTimeout: -1.0, tag: PacketTag.body.rawValue)
    }
```

So yes, the actual communication you have in mind has nothing to do with Bonjour/Zeroconf/etc. and you need a pair of server/client sockets to exchange the actual data over (TCP or UDP, depends on your use case).
