### ISSUE TITLE
How can I use Python-Zeroconf to "Publish a service"?

### ISSUE THREAD

**Issue by taichi-suzuki-pckg** [jstasiak/python-zeroconf#310]
How can I use Python-Zeroconf to "Publish a service"?

This example uses a different library, but is it possible to do this with Python-Zeroconf as well?
Here's what I want to do:
[https://serverfault.com/questions/118237/how-to-use-zeroconf
](https://serverfault.com/questions/118237/how-to-use-zeroconf
)
```
from ZeroconfService import ZeroconfService
service = ZeroconfService (name = "Joe's awesome FTP server",
                           port = 3000, stype = "_ ftp._tcp")
service.publish ()
```

There is a function called "register_service" in the [Zeroconf API documentation](https://python-zeroconf.readthedocs.io/en/latest/api.html), can I do the same with it?

**Comment by jstasiak** [comment]
Yes, see the service registration example to see how it's used: https://github.com/jstasiak/python-zeroconf/blob/master/examples/registration.py
