### ISSUE TITLE
Allow >15 character service_type_name when strict is False

### ISSUE THREAD

**Issue by garethsb** [jstasiak/python-zeroconf#311]
I saw that 0.28.6 has added a more relaxed service type name checking mode, not just allowing underscores.

Bonjour also allows mDNS service type names longer than 15 characters in fact, despite the clear requirement in RFC6335.
We have dealt with deployments using overlong names by monkey patching python-zeroconf to skip the `len(test_service_name) > 15` check.

So I hoped `strict=False` would work for me.

However, I see that the condition for doing most of the checks is now `strict or has_protocol`... why not just `strict`?

Thanks!

**Comment by bdraco** [comment]
Is this still a problem with the latest version?

Do you need to accept these names or register them?

Thanks

**Comment by garethsb** [comment]
I believe this is still a small issue for us, though I haven't checked latest recently. The line I was referring to is
https://github.com/jstasiak/python-zeroconf/blob/beccad1f0b41730f541b2e90ea2eaa2496de5044/zeroconf/__init__.py#L294

CC: @andrewbonney

**Comment by bdraco** [comment]
Closed via https://github.com/jstasiak/python-zeroconf/pull/666

**Comment by garethsb** [comment]
Thanks 👍
