### ISSUE TITLE
Can't find Service without running for loop multiple times?

### ISSUE THREAD

**Issue by taichi-suzuki-pckg** [jstasiak/python-zeroconf#312]
I want to search for Bonjour Service.
First of all, I ran the following code, but nothing was detected and the code exited without any error

```
from zeroconf import ServiceBrowser, Zeroconf
from socket import inet_ntoa

class MyListener:
	def __init__(self):
		self.ipaddress = None
		
	def remove_service(self, zeroconf, type, name):
		print("Service %s removed" % (name,))

	def add_service(self, zeroconf, type, name):
		info = zeroconf.get_service_info(type, name)
		self.ipaddress = inet_ntoa(info.addresses[0])
	
zeroconf = Zeroconf()
listener = MyListener()

try:
	browser = ServiceBrowser(zeroconf, "_testBonjour._tcp.local.", listener)
	if not listener.ipaddress == None:
		print(listener.ipaddress)
except:
	pass

zeroconf.close()
```

Then I ran the following code to search for the Service.
I just added 2000 loops to the code above. 
This code worked and was able to find the IP address of the Service. 

```
from zeroconf import ServiceBrowser, Zeroconf
from socket import inet_ntoa

class MyListener:
	def __init__(self):
		self.ipaddress = None
		
	def remove_service(self, zeroconf, type, name):
		print("Service %s removed" % (name,))

	def add_service(self, zeroconf, type, name):
		info = zeroconf.get_service_info(type, name)
		self.ipaddress = inet_ntoa(info.addresses[0])
	
zeroconf = Zeroconf()
listener = MyListener()

for i in range(2000):
	try:
		browser = ServiceBrowser(zeroconf, "_testBonjour._tcp.local.", listener)
		if not listener.ipaddress == None:
			print(listener.ipaddress)
			break
	except:
		pass

zeroconf.close()
```

Is my way of writing code like this correct? 
It takes a long time to detect, and I don't think it's very natural code. 
Please let me know if my code is something wrong.

**Comment by jstasiak** [comment]
Yes, neither of your examples will work. `ServiceBrowser(..., listener, ...)` is not a synchronous action where listener gets notified right away – it spawns a background thread that'll call your listener when the relevant data arrives from the network (if ever). You need to contruct an instance of `ServiceBrowser`, keep it around and *wait*. By constructing `ServiceBrowser` instances, testing the listener changes right away and moving on (either closing the application or creating another instance of `ServiceBrowser`) you don't give the library the time it needs to do its work behind the scenes.

See https://github.com/jstasiak/python-zeroconf/blob/master/examples/browser.py for reference.

**Comment by jstasiak** [comment]
PS. Also the
```python
        try:
            # ...
	except:
		pass
```

block doesn't do you any favors as it'll hide issues you likely want to know about.

**Comment by taichi-suzuki-pckg** [comment]
Thank you!
This solved the problem!
