### ISSUE TITLE
Provide scope_id when resolving IPv6 Link Local addresses

### ISSUE THREAD

**Issue by ghost** [jstasiak/python-zeroconf#314]
When a service is advertised over an IPv6 Link local address (i.e. fe80::/64), a non-global scope address, the resolved IPv6 address information returned by ServiceInfo must be extended with the `scope_id` field after the `%` symbol (see RFC 4007) to allow correct identification of the local interface to use when routing to that IPv6 Link Local address.

**Comment by adeaet** [comment]
This issue is addressed by the following proposed PR: https://github.com/jstasiak/python-zeroconf/pull/315

**Comment by en-dps-dev-sk** [comment]
This issue has not been orphaned; internal change in how we organise branches means a new pull request will be opened in due course.
