### ISSUE TITLE
[Question] Browsing service

### ISSUE THREAD

**Issue by Frantisekf** [jstasiak/python-zeroconf#328]
Hi, first of all thanks for this library.I'm very new to this stuff and also haven't done much python so I wanted to ask for help regarding browsing for services. What I'm trying to achieve is to discover services and then store them as objects into a list. Basically something in the following lines although I would probably need for the on_service_state_change function to return an object if that's possible. the main thing I wanted to ask is how to execute the discovery in such scenario where I need the browser to resolve and end the event loop after finishing with the service discovery

```
def on_service_state_change(
    zeroconf: Zeroconf, service_type: str, name: str, state_change: ServiceStateChange
) -> None:
    print("Service %s of type %s state changed: %s" % (name, service_type, state_change))

    if state_change is ServiceStateChange.Added:
        info = zeroconf.get_service_info(service_type, name)
        print("Info from zeroconf.get_service_info: %r" % (info))
        if info:
            addresses = ["%s:%d" % (addr, cast(int, info.port)) for addr in info.parsed_addresses()]
            print("  Addresses: %s" % ", ".join(addresses))
            print("  Weight: %d, priority: %d" % (info.weight, info.priority))
            print("  Server: %s" % (info.server,))
            if info.properties:
                print("  Properties are:")
                for key, value in info.properties.items():
                    print("    %s: %s" % (key, value))
            else:
                print("  No properties")
        else:
            print("  No info")
        print('\n')        


class ServicesRoute(Resource):
    logging.basicConfig(level=logging.DEBUG)

    def get(self):
        shelf = get_db()
        keys = list(shelf.keys())

        ip_version = IPVersion.All
        zeroconf = Zeroconf(ip_version=ip_version)

        services = list(ZeroconfServiceTypes.find(zc=zeroconf))

        browser = ServiceBrowser(zeroconf, services, handlers=[on_service_state_change])

        servicesDiscovered = []

        for key in servicesDiscovered:
            servicesDiscovered.append(shelf[key])

        return {'message': 'Success', 'services': servicesDiscovered}, 200 
```

**Comment by jstasiak** [comment]
Hey, nice to hear you're finding it useful. If you want to collect the information you can use the following pattern (pass a method of an object as a handler, you'll be able to store the data in the object's properties):

```python

class Collector:
    def __init__(self):
        self.infos = []

    def on_service_state_change(
        self, zeroconf: Zeroconf, service_type: str, name: str, state_change: ServiceStateChange
    ) -> None:
        print("Service %s of type %s state changed: %s" % (name, service_type, state_change))
    
        if state_change is ServiceStateChange.Added:
            info = zeroconf.get_service_info(service_type, name)
            print("Info from zeroconf.get_service_info: %r" % (info))
            if info:
                addresses = ["%s:%d" % (addr, cast(int, info.port)) for addr in info.parsed_addresses()]
                print("  Addresses: %s" % ", ".join(addresses))
                print("  Weight: %d, priority: %d" % (info.weight, info.priority))
                print("  Server: %s" % (info.server,))
                if info.properties:
                    print("  Properties are:")
                    for key, value in info.properties.items():
                        print("    %s: %s" % (key, value))
                else:
                    print("  No properties")
            self.infos.append(info)  # <--------------------------------
            else:
                print("  No info")
            print('\n')       
``` 

And then in the code using the library:

```python
collector = Collector()
rowser = ServiceBrowser(zeroconf, services, handlers=[collector.on_service_state_change])
```

and then after the discoveries happened you can get the information from `collector.infos`.

There's one thing though – creating `ServiceBrowser` creates a thread that queries for services and listeners to responses, calling the handler when it receives one. It's not a synchronous operation and it happens in the background. Once you've created `ServiceBrowser` you need to wait for the responses using `time.sleep()` or similar. How much do you want or you can afford to wait is something only you can tell. If you want to be able to access this information immediately I advice you create one `ServiceBrowser` for your whole application, make it store the date in some variable that you can always access from the `get()` method of your class and then just use it from there.

**Comment by Frantisekf** [comment]
Thanks a million for the response. I thinks this is pretty much what I'm looking for. so gonna try that :)

**Comment by Frantisekf** [comment]
So I tried to add time.sleep() as a temporary solution just to try it out but I got this error 
`Exception in thread Thread-7:
Traceback (most recent call last):
 File "/usr/local/lib/python3.9/threading.py", line 954, in _bootstrap_inner
 self.run()
 File "/usr/local/lib/python3.9/site-packages/zeroconf/__init__.py", line 1733, in run
 next_time = min(self._next_time.values())
ValueError: min() arg is an empty sequence`

**Comment by jstasiak** [comment]
Please provide an exact version of Python and python-zeroconf you're running and a self-contained piece of code to reproduce this.

**Comment by Frantisekf** [comment]
Here is the code pieces 
https://github.com/Frantisekf/zeroconf-service-discovery-API/blob/master/service_discovery/__init__.py

I'm running it in a docker environment with python3 version and version of zeroconf 0.28.8

Here is the snippet that's causing the issue
```
class Collector:
    def __init__(self):
        self.infos = []

    def on_service_state_change(
        self, zeroconf: Zeroconf, service_type: str, name: str, state_change: ServiceStateChange
    ) -> None:
        print("Service %s of type %s state changed: %s" % (name, service_type, state_change))
    
        if state_change is ServiceStateChange.Added:
            info = zeroconf.get_service_info(service_type, name)
            print("Info from zeroconf.get_service_info: %r" % (info))
            if info:
                addresses = ["%s:%d" % (addr, cast(int, info.port)) for addr in info.parsed_addresses()]
                print("  Addresses: %s" % ", ".join(addresses))
                print("  Weight: %d, priority: %d" % (info.weight, info.priority))
                print("  Server: %s" % (info.server,))
                if info.properties:
                    print("  Properties are:")
                    for key, value in info.properties.items():
                        print("    %s: %s" % (key, value))
                else:
                    print("  No properties")
            self.infos.append(info)  # <--------------------------------


class ServicesRoute(Resource):
    logging.basicConfig(level=logging.DEBUG)

    def get(self):
        shelf = get_db()
        keys = list(shelf.keys())
        servicesDiscovered = []

        ip_version = IPVersion.V4Only
        zeroconf = Zeroconf(ip_version=ip_version)

        services = list(ZeroconfServiceTypes.find(zc=zeroconf))

        collector = Collector()
        browser = ServiceBrowser(zeroconf, services, handlers=[collector.on_service_state_change])
        time.sleep(10)


        for key in collector.infos:
            servicesDiscovered.append(shelf[key])

        return {'message': 'Success', 'services': servicesDiscovered}, 200
```

**Comment by Frantisekf** [comment]
ah, okay I managed to find the problem it was in the docker-compose configuration.

**Comment by xavierchan** [comment]
> ah, okay I managed to find the problem it was in the docker-compose configuration.

Hi, i get the same problem as you, how did you fix the problem with docker-compose configuration?
