### ISSUE TITLE
[Question] How to make addresses list all the addresses for one PC in one ServiceInfo?

### ISSUE THREAD

**Issue by liupoer** [jstasiak/python-zeroconf#329]
Hi
      I run a avahi service in one PC.  And it is showing services for every interface. As below:

- =;docker0;IPv4;nmos\032controller\032tsn;_nmos-register._tcp;local;tsn.local;172.17.0.1;5100;"pri=0" "api_auth=false" "api_ver=v1.3" "api_proto=http"
- =;enp1s0f1;IPv4;nmos\032controller\032tsn;_nmos-register._tcp;local;tsn.local;192.168.1.2;5100;"pri=0" "api_auth=false" "api_ver=v1.3" "api_proto=http"
- =;enp3s0;IPv4;nmos\032controller\032tsn;_nmos-register._tcp;local;tsn.local;10.193.20.38;5100;"pri=0" "api_auth=false" "api_ver=v1.3" "api_proto=http"
- =;lo;IPv4;nmos\032controller\032tsn;_nmos-register._tcp;local;localhost;127.0.0.1;5100;"pri=0" "api_auth=false" "api_ver=v1.3" "api_proto=http"

But when I get serviceInfo in the python code. I got only the first address in the serviceInfo's addresses:
    ServiceInfo(type='_nmos-register._tcp.local.', name='nmos controller tsn._nmos-register._tcp.local.', addresses=[b'\xac\x11\x00\x01'], port=5100, weight=0, priority=0, server='tsn.local.', properties={b'api_proto': b'http', b'api_ver': b'v1.3', b'api_auth': b'false', b'pri': b'0'})

What should I set it to list them all?
Thanks!

**Comment by liupoer** [comment]
I found these interfaces were called by update callback.

**Comment by jstasiak** [comment]
Thank you for the report. Please provide the OS you're running (Kernel version at least), the exact Python version and the version of python-zeroconf you're using.

Can you decode this part? How do you get this output and what's the meaning of all the parts of those lines?

```
    =;docker0;IPv4;nmos\032controller\032tsn;_nmos-register._tcp;local;tsn.local;172.17.0.1;5100;"pri=0" "api_auth=false" "api_ver=v1.3" "api_proto=http"
    =;enp1s0f1;IPv4;nmos\032controller\032tsn;_nmos-register._tcp;local;tsn.local;192.168.1.2;5100;"pri=0" "api_auth=false" "api_ver=v1.3" "api_proto=http"
    =;enp3s0;IPv4;nmos\032controller\032tsn;_nmos-register._tcp;local;tsn.local;10.193.20.38;5100;"pri=0" "api_auth=false" "api_ver=v1.3" "api_proto=http"
    =;lo;IPv4;nmos\032controller\032tsn;_nmos-register._tcp;local;localhost;127.0.0.1;5100;"pri=0" "api_auth=false" "api_ver=v1.3" "api_proto=http"
```

It seems like you're receiving a service advertisement on every network interface but every advertisement has a different address but I can't tell for sure without knowing what do those lines mean, exactly.

Could you maybe provide python-zeroconf debug output coming from your application? (the `zeroconf` logger's level needs to be set to `DEBUG`).

**Comment by jstasiak** [comment]
A sample application that reproduces this would be nice as well.

**Comment by liupoer** [comment]
Hi Jacub,
     You are right, they are ports in one same PC I tested. The mdns server running by the avahi in the same PC. And the result got by the avahi-browser command. So I can get many addresses for all the ports in one same PC. The application could run in same PC to report its resource.
     ` 45     def _resolve_service(self, srv_type, name, act_type):
 46         self.resolve_queue.put((srv_type, name, act_type))
 47         t = Thread(target=self.worker)
 48         t.daemon = True
 49         t.start()
 50
 51     def add_service(self, zeroconf, srv_type, name):
 52         print("service {} : name is {} added ".format( srv_type, name))
 53         self._resolve_service(srv_type, name, SERVICE_ACTION[0])
 54
 55     def remove_service(self, zeroconf, srv_type, name):
 56         print("service ({}) : name ({})removed".format(srv_type, name))
 57         self._resolve_service(srv_type, name, SERVICE_ACTION[1])
 58
 59     def update_service(self, zeroconf, srv_type, name):
 60         self._resolve_service(srv_type, name, SERVICE_ACTION[2])
 61
62     def get_service_list(self):
 63         self.resolve_queue.join()
 64         return self.services
 65
 66     def worker(self):
 67         item = self.resolve_queue.get()
 68         if item[2] not in SERVICE_ACTION:
 69             self.resolve_queue.task_done()
 70             return
 71         if item[2] == SERVICE_ACTION[0]:
 72             info = self.zeroconf.get_service_info(item[0], item[1])
 73             if info is not None:
 74                 self.services.append(info)
 75                 print("info add")
 76         elif item[2] == SERVICE_ACTION[1]:
 77             info = self.zeroconf.get_service_info(item[0], item[1])
 78             for service in self.services:
 79                 if service.type == item[0] and service.name == item[1]:
 80                     self.services.remove(service)
 81                     print("info removed")
 82
 83         else:
 84             info = self.zeroconf.get_service_info(item[0], item[1])
 85             print(info)
 86             for service in self.services:
 87                 if service.type == item[0] and service.name == item[1]:
 88                     self.services.remove(service)

`
    
[log.txt](https://github.com/jstasiak/python-zeroconf/files/6080631/log.txt)

Thanks!

**Comment by liupoer** [comment]
Hi Jakub,
     I am not sure about this. I suppose the report serviceInfo should include all the ports to the 'addresses'.
I do see it is list in the log:
`DEBUG:zeroconf:Listen socket <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 5353)>, respond sockets [<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('127.0.0.1', 5353)>, <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('192.168.1.2', 5353)>, <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('172.17.0.1', 5353)>, <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('10.193.20.38', 5353)>]`

But from what I got in the service_browser. It is only showing one address, but updated for next:
info update
`ServiceInfo(type='_nmos-register._tcp.local.', name='nmos controller tsn._nmos-register._tcp.local.', addresses=[b'\n\xc1\x14&'], port=5100, weight=0, priority=0, server='tsn.local.', properties={b'api_proto': b'http', b'api_ver': b'v1.3', b'api_auth': b'false', b'pri': b'0'})`
Is it normal?

Best regards!
Po Liu

**Comment by ibiltari** [comment]
Same behavior here, in another app we are making. Sometimes extra interfaces are added with the update method, sometimes not. Always picks at least one in the add method, but is not always the same one, so it gets worse.

Good job!!
Ion

**Comment by bdraco** [comment]
￼This was a bug, it should be fixed on master. Please re-open if it's still a problem￼
