### ISSUE TITLE
Should not bind to all interfaces by default

### ISSUE THREAD

**Issue by jjlawren** [jstasiak/python-zeroconf#330]
Since the changes in #270/#188, the default behavior is to listen & broadcast on all available interfaces. Since we work with multicast, every other interface can see the broadcast. We end up reading our own sent packets which results in broadcast storms that overwhelm the host/network.

This is _especially_ problematic on busy Docker hosts. In these setups each container will add another interface/bridge to the box which amplifies the issue.

This behavior can be overridden by explicitly choosing an interface when instantiating but this new default seems dangerous.

**Comment by bdraco** [comment]
I’ll take a run at this as I’ve seen this as well and it explains the duplicates

**Comment by bdraco** [comment]
I think we can add an interface choice of unspecified and simply bind to '' and disable the duplicate packet check when set.  Home assistant could then set this as the default.  It should also solve the excessive chatty ness bonjor conformance test failing

**Comment by bdraco** [comment]
To fully pass the bonjor conformance test we would also need to implement handling of MU flags since we should only reply unicast when that's set if the time since last broadcast is less then x percent of the total to avoid broadcasts when the query doesn't need to go to the whole network
