### ISSUE TITLE
One shot scanner?

### ISSUE THREAD

**Issue by hyansuper** [jstasiak/python-zeroconf#336]
Is there an one shot scanner api that returns immediately instead of the browserService which runs a background thread?

**Comment by bdraco** [comment]
Are you scanning for a specific service type? Or do you just want to discover everything?

**Comment by hyansuper** [comment]
I am scanning for a specific service type

**Comment by bdraco** [comment]
https://github.com/jstasiak/python-zeroconf/blob/master/examples/async_browser.py

You could do everything in async and then just cancel the instance as soon as you find the service.

**Comment by hyansuper** [comment]
Thank you. That's good
