### ISSUE TITLE
Crashes with version 0.29, but works fine with version 0.28.8

### ISSUE THREAD

**Issue by peter-hardman** [jstasiak/python-zeroconf#346]
If I have version 0.29.0 loaded I see the following failure messages.  They are gone with the previous version.

 /find_units.py", line 204, in __init__
    self.zeroconf = Zeroconf()
\zeroconf\__init__.py", line 2509, in __init__
    interfaces, unicast, ip_version, apple_p2p=apple_p2p
 \zeroconf\__init__.py", line 2343, in create_sockets
    respond_socket = new_respond_socket(i, apple_p2p=apple_p2p)
\zeroconf\__init__.py", line 2305, in new_respond_socket
    bind_addr=cast(Tuple[Tuple[str, int, int], int], interface)[0] if is_v6 else (cast(str, interface),),
\zeroconf\__init__.py", line 2250, in new_socket 
s.bind((bind_addr[0], port, *bind_addr[1:]))
OSError: [WinError 10049] The requested address is not valid in its context

Any time I try to instantiate an item from the Zeroconf package I see this error.
Machine is Windows 10.

**Comment by bdraco** [comment]
This should be resolved in 0.30.0.  Please reopen if you are still seeing the issue.

**Comment by peter-hardman** [comment]
Thanks. All working now.
