### ISSUE TITLE
[Bug] Changing the _BROWSER_BACKOFF_LIMIT does nothing

### ISSUE THREAD

**Issue by SeiteBroken** [jstasiak/python-zeroconf#359]
I changed _BROWSER_BACKOFF_LIMIT to reduce the time until a service gets unregistered, but it didn't change anything.

**Comment by bdraco** [comment]
Browser backoff limit is for the progressive back off of sending queries to update records in the ServiceBrowser.

Please read https://datatracker.ietf.org/doc/html/rfc6762#section-5.2

**Comment by bdraco** [comment]
This has gone stale. I'm going to close it out
