### ISSUE TITLE
Discover arduino services

### ISSUE THREAD

**Issue by gepd** [jstasiak/python-zeroconf#43]
Hi, I'm new with mDNS, I've found this library but I'm not sure how to do what I want to do.

I need to list all the Arduino devices in my network, same as the official arduino IDE does. I've tried the examples, but none of them show me the arduino device, I know it's all fine with the device because when I open the IDE it shows me the device with it corresponding ip

Can this library do this?

Any help will be appreciated.

**Comment by strahlex** [comment]
Very likely a `_workstation._tcp` lookup showing all hosts on the network with running avahi-daemon.

**Comment by nameoftherose** [comment]
If you are still looking for an answer, zeroconf can do what you want, provided the arduinos advertise themselves on the local network. You have to know what service they adverise, as mentioned above, it may be _workstation, or _http. Then you must modify and run the browser.py example (browser may be modified to simultaneously look for more than one type of service). 
I am doing this with esp8266 whose software is an arduino clone. If you have more questions drop me a line and I will try to help.
If you are using linux avahi and avahi-browse will also discover your arduinos.
In both cases arduinos must advertise their services, ie they must be running mdns-sd not just mdns. If they run just an mdns responder you can discover their ip but you have to know their names.

**Comment by gepd** [comment]
Thanks @strahlex and @nameoftherose for your answers

Until now all seems to work well with: `browser = ServiceBrowser(zeroconf, "_arduino._tcp.local.", handlers=[on_service_state_change])`

I've tested with an Arduino Yun without problems

**Comment by stephenrauch** [comment]
I just submitted PR #48 which will hopefully make discovering the service type name easier in the future.

@gepd if you have resolved your problem, you may want to close this Issue.

**Comment by gepd** [comment]
Thanks all of you
