### ISSUE TITLE
connection is refused

### ISSUE THREAD

**Issue by sprhawk** [jstasiak/python-zeroconf#46]
I set up a service like this:

```
TYPE = "_motion._tcp.local."
NAME = "_yyyyXXXX." + TYPE
PORT = 4321

logging.basicConfig(level=logging.DEBUG)
logging.getLogger("zeroconf").setLevel(logging.DEBUG)

zeroconf = Zeroconf()

def reg_srv():
    info = ServiceInfo(TYPE,
            NAME,
            socket.inet_aton("127.0.0.1"), PORT, 0, 0,
            {"desc":"HOME Bonjour test"})


    zeroconf.register_service(info)
```

I use `nc -l 4321` to receive connection.

But socket ( from a remote computer or phone ) reported connection refused.

When I turned to use `dns-sd -R "XXX" "_motion._tcp" "local" 4321` it works well.

What am I missing ?

**Comment by sprhawk** [comment]
I found it may be due to socket.inet_aton("127.0.0.1").

But how should I set this address value to suit a dynamic ip address ?

**Comment by sprhawk** [comment]
I changed with:

```
    socket_addr = socket.gethostbyname(socket.gethostname())
    info = ServiceInfo(TYPE,
            NAME,
            socket.inet_aton(socket_addr), PORT, 0, 0,
            {"desc":"HOME Bonjour test"})
```

how to support ipv4 and ipv6 address simultaneously ?

with ` socket.getaddrinfo()` ?

**Comment by bdraco** [comment]
`ServiceInfo` gained an `addresses` field a few versions back that supports v4 and v6 addresses
