### ISSUE TITLE
Discover IPv6 services

### ISSUE THREAD

**Issue by jgoguen** [jstasiak/python-zeroconf#52]
I'm trying to discover IPv6-only and dual-stacked services and only the IPv4 address of the dual-stacked services are being discovered. Using avahi I can discover the IPv6 services and both addresses of dual-stacked services, and I can use those services on the IPv6 addresses. This happens with every service I've tried (_airplay._tcp, _ipp._tcp, _http._tcp, _ssh._tcp).

Ideally, I would like to be able to specify how to handle IPv6 services:
- Do not show IPv6, only IPv4
- Prefer IPv4, search for both (default)
- Prefer IPv6, search for both
- Do not show IPv4, only IPv6

When both exist, only one service should be returned according to the precedence desired.

**Comment by stephenrauch** [comment]
Looking at the code, it currently has:

```python
def new_socket():
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
```

So, it does not even attempt IPV6, at the very least it would need something along the lines of:

```python 
    s = socket.socket(socket.AF_INET6, socket.SOCK_DGRAM)
```

And the bind would need to change, and some of the setsockopt() calls would also need to change. That would be just to start the connection.  Also needed would be some code to distinguish when it had connected to the same guys on two different addresses.

Sounds like a great feature, but it will be a non-trivial amount of work.

**Comment by edmont** [comment]
+1

**Comment by dtantsur** [comment]
I would like to work on IPv6 support if nobody minds.

**Comment by edmont** [comment]
@dtantsur that sounds great!

**Comment by jstasiak** [comment]
@dtantsur I believe it'll be appreciated. I'm not sure about the API but the general principle described by @jgoguen seems reasonable.

**Comment by dtantsur** [comment]
@jstasiak right, yeah.

My biggest problem right now is that IPv6 has a different API for joining a multicast group. Instead of accepting (multicast address, interface address) it accepts (multicast address, interface index). This index is not trivial to get from an interface address even on POSIX systems, and is a nightmare on Windows. I'd appreciate any hints on how to get from `interfaces=["fe80::cb0f:..."]` to 3 (which is interface index for me), especially on Windows.

**Comment by jstasiak** [comment]
I'm afraid I won't be able to help with this, I haven't really worked with IPv6, I hope some more familiar with the subject sees this though.

**Comment by dtantsur** [comment]
No worries, I'll try to figure this out.

I guess my question is how receptive you would be to a solution that has a different interface or some limitation compared to IPv4?

**Comment by jstasiak** [comment]
As long as it provides value to IPv6 users (I'm not one of them at the moment so you be the judge here), doesn't break IPv4 users (or does it after discussion) and has a reasonable interface I don't see any issue with it. When you know what the interface difference or limitations will be I'm happy to comment further, but in general I expect the project to be receptive. :)

**Comment by dtantsur** [comment]
If you're curious, this is my current struggle: https://twitter.com/creepy_owlet/status/1131122252509044736
