### ISSUE TITLE
zeroconf.BadTypeInNameException for valid service name

### ISSUE THREAD

**Issue by nils-werner** [jstasiak/python-zeroconf#74]
With 0.17.6 service names like

    6d86f882b90facee9170ad3439d72a4d6ee9f511._zget._http._tcp.local

stopped working. I was under the impression that service names [had to be designed like this](https://tools.ietf.org/html/rfc6763#section-7.2). Is this assumption wrong or is your [service name validator](https://github.com/jstasiak/python-zeroconf/commit/88fa0595cd880b6d82ac8580512461e64eb32d6b) too strict?

**Comment by stephenrauch** [comment]
This is not a valid name according to my understanding of RFC6763.  The comments in that part of the code (the validator) are quite extensive.  Take a look, if it doesn't make sense, or you still think the code is wrong please let me know.  The RFC is [here](https://tools.ietf.org/html/rfc6763#page-19).  It is sadly not the easiest of reads.

**Comment by stephenrauch** [comment]
@nils-werner 

Thanks so much for reporting this problem.  A fix has been [merged](
https://github.com/jstasiak/python-zeroconf/commit/9035c6a246b6856b5087b1bba9a9f3ce5873fcda).

It can easily be installed with:

```
pip install https://github.com/jstasiak/python-zeroconf/archive/develop.zip
```

It would very helpful if you could give it a try and report back.

Thanks again.

**Comment by nils-werner** [comment]
It seems to fix it, thanks!

**Comment by jasongaiser** [comment]
Any chance we'll see a new release containing this fix anytime soon?  I'm happy to help if needed.
