### ISSUE TITLE
Services registered w/ 17.7.dev are not visible to ServiceBrowser

### ISSUE THREAD

**Issue by gbiddison** [jstasiak/python-zeroconf#76]
I am debugging this issue at the moment to try to get more details, I am having a problem in 17.7.dev either with browsing or registration.  

I have approx. 30 services running 0.17.6.  If my service browser is running 0.17.6 or 0.17.7.dev, I recover all of these services.

However, if any of the services are upgraded to 0.17.7.dev, then the service browser no longer recovers that specific service.  

Using 'bonjour browser' on OSX, I do see all 30 services regardless of zeroconf version, so the registration appears to be succeeding.  

I will continue to debug this, but any suggestions are welcome.

**Comment by stephenrauch** [comment]
To summarize, a 17.7.dev browser cannot see a 17.7.dev advertiser?  But other combination seem to work?

**Comment by gbiddison** [comment]
Yes.  I have isolated it to def write_name  (the compressed name code in 17.7.dev).  Replacing this method w/ the version from 17.6 resolves the issue.

**Comment by gbiddison** [comment]
And to improve your summary - a 17.7.dev browser cannot see a 17.7.dev advertiser, but can see a 17.6 advertiser.   I have not been able to see a 17.7.dev advertiser in a 17.6 browser.

**Comment by gbiddison** [comment]
To be more specific about what works for me:

```diff
diff --git a/zeroconf.py b/zeroconf.py
index a192e4b..df91f7e 100644
--- a/zeroconf.py
+++ b/zeroconf.py
@@ -883,49 +883,28 @@ class DNSOutgoing(object):
         self.write_string(value)
 
     def write_name(self, name):
-        """
-        Write names to packet
-
-        18.14. Name Compression
-
-        When generating Multicast DNS messages, implementations SHOULD use
-        name compression wherever possible to compress the names of resource
-        records, by replacing some or all of the resource record name with a
-        compact two-byte reference to an appearance of that data somewhere
-        earlier in the message [RFC1035].
-        """
-
-        # split name into each label
-        parts = name.split('.')
-        if not parts[-1]:
-            parts.pop()
-
-        # construct each suffix
-        name_suffices = ['.'.join(parts[i:]) for i in range(len(parts))]
-
-        # look for an existing name or suffix
-        for count, sub_name in enumerate(name_suffices):
-            if sub_name in self.names:
-                break
-        else:
-            count += 1
-
-        # note the new names we are saving into the packet
-        for suffix in name_suffices[:count]:
-            self.names[suffix] = self.size + len(name) - len(suffix) - 1
+        """Writes a domain name to the packet"""
 
-        # write the new names out.
-        for part in parts[:count]:
-            self.write_utf(part)
+        if name in self.names:
+            # Find existing instance of this name in packet
+            #
+            index = self.names[name]
 
-        # if we wrote part of the name, create a pointer to the rest
-        if count != len(name_suffices):
-            # Found substring in packet, create pointer
-            index = self.names[name_suffices[count]]
+            # An index was found, so write a pointer to it
+            #
             self.write_byte((index >> 8) | 0xC0)
             self.write_byte(index & 0xFF)
         else:
-            # this is the end of a name
+            # No record of this name already, so write it
+            # out as normal, recording the location of the name
+            # for future pointers to it.
+            #
+            self.names[name] = self.size
+            parts = name.split('.')
+            if parts[-1] == '':
+                parts = parts[:-1]
+            for part in parts:
+                self.write_utf(part)
             self.write_byte(0)
 
     def write_question(self, question):
```

**Comment by stephenrauch** [comment]
Thanks, there may be a problem with the name compression code that is related to #74.  My understanding was (and for that matter may still be) incomplete as to the usage of '.'  Can you post a typical name as it appear on your network?  There may also be a latent bug in the read_name code which is responsible for unwinding the name compression.

Above you said bonjour was happy, that fact combined with your improved summary  would make me lean towards the problem being a latent issue in read_name().

**Comment by gbiddison** [comment]
Typical name ```SolidStateSynthesizerModule-10._synthego-inst._tcp.local.``` passed to ServiceInfo as the 'name' parameter.  

Typically the part left of the first '.' is a dns host name, and everything else is service info 'type' (e.g. ```_synthego-inst._tcp.local.```)

**Comment by gbiddison** [comment]
I think this may be it; index calculation is wrong in write_name:

```diff
diff --git a/zeroconf.py b/zeroconf.py
index a192e4b..b87fdf2 100644
--- a/zeroconf.py
+++ b/zeroconf.py
@@ -911,8 +911,10 @@ class DNSOutgoing(object):
             count += 1
 
         # note the new names we are saving into the packet
-        for suffix in name_suffices[:count]:
-            self.names[suffix] = self.size + len(name) - len(suffix) - 1
+        index_offset = 0
+        for suffix in enumerate(name_suffices[:count]):
+            self.names[suffix] = self.size + index_offset
+            index_offset += len(suffix)
 
         # write the new names out.
         for part in parts[:count]:
```

This resolves the issue without removing the compression code.

**Comment by stephenrauch** [comment]
So I got chance to test the above, and it solves the problem by effectively turning off the name compression.  I assume, this is true because whatever ends up in self.names never matches.  [Wireshark](https://www.wireshark.org/) happily parses the packets the original name compression code generates, so the packets are in the ballpark.  I don't know if you are familiar with [wireshark](https://www.wireshark.org/), but if I could see a network trace that might help debugging this.

What OS are you running this under?

**Comment by gbiddison** [comment]
It's a mixed OSX El Capitan / Ubuntu 14.04 network.  I've run the service browser on both OSes and don't see a difference.  I've also run the service advertistements on both OSes and the result is the same in all permutations of OS browser/service.  I'll see if I can get a network trace.  
I haven't used wireshark in years.

**Comment by gbiddison** [comment]
Indeed there is a problem in that last patch I proposed; I'd accidentally left the 'enumerate' in there from an earlier test; so you're right, that code is just generating unusable entries in the self.names cache and bypassing the compression altogether.  Removing 'enumerate'  from the loop gets the code I meant to post.

```diff
diff --git a/zeroconf.py b/zeroconf.py
index a192e4b..b62af20 100644
--- a/zeroconf.py
+++ b/zeroconf.py
@@ -911,8 +911,10 @@ class DNSOutgoing(object):
             count += 1
 
         # note the new names we are saving into the packet
+        index_offset = 0
         for suffix in name_suffices[:count]:
-            self.names[suffix] = self.size + len(name) - len(suffix) - 1
+            self.names[suffix] = self.size + index_offset
+            index_offset += len(suffix)
 
         # write the new names out.
         for part in parts[:count]:
```
Apologies for the wasted effort.  I believe I have another smaller patch that also solves the issue for me, I should be able to post that shortly.

**Comment by gbiddison** [comment]
I think that the above works may indicate that there is an error in the name reading code ... 

My understanding of what's happening here on the name write is that there is a cache (self.names) which is a dictionary keyed by 'name part' with values of 'offset' where offset is an index into some data-frame (self.data) that is being transmitted.

The compression works by replacing redundant name parts with their offset to previous 
locations where they were defined in the data-frame.

The 'name-parts' are cyclic permutations of the service name, where each cycle removes a component of the name starting from the left up to the next period.  So if the name starts as 'foo.bar.baz.', the 'parts' of this name are 'foo.bar.baz.', 'bar.baz.' and 'baz.'  Each of these is pushed into the-data frame when first encountered (via write-utf), and pushed into the name cache with an offset corresponding to where they would be written into the data-frame.

During processing of the same "DNSOutgoing" construction, any new name-parts are written out in full, but if any name-parts of the current name are found in the cache, then a single offset is written instead, corresponding to the largest cyclic permutation of the name that was not found.  For example, if a new name 'test.bar.baz.' was found while processing the same DNSOutgoing that processed 'foo.bar.baz.', the 'test.' part would be written to the data-frame and name cache, and the 'bar.baz.' chunk would be substituted with the offset of the original string.

In the original code, all parts of the original name are pushed consecutively to the data-frame, but the offsets are all recorded relative to the longest name.  For example - if the name was 'foo.bar.baz.', the code would write 'foo.bar.baz.' at self.size + 0, 'bar.baz.' at self.size + 12, and 'baz.' at self.size + 20  (please forgive off by 1 errors here).  It would also update the name cache offsets, but the offsets would all refer to offsets within the full 'foo.bar.baz.' component.  So the name-cache offsets would be self.size + 0, self.size + 4, and self.size + 8 respectively (again, possibly off by one, I don't quite understand the -1 part of the math when adding values to this cache).

This appears to be valid packet construction; as does my alternative, which is to update the name-cache with the full offsets to the individual name-parts rather than to sub-strings of the first name-part.

I don't have an explanation for why the original code isn't working on my network (I agree that it should), but hope this presents the reasoning for the change I've outlined that just makes it work.   

I will try to analyze the read code to see if I can find a reason there.

**Comment by gillima** [comment]
Same issue with Ubuntu 16.04, Advertisement could not be resolved by avahi-browse, The patch above fixed this for me.

**Comment by bdraco** [comment]
@gbiddison Is this still an issue on `master`?
