### ISSUE TITLE
deque mutated during iteration

### ISSUE THREAD

**Issue by gbiddison** [jstasiak/python-zeroconf#78]
I'm seeing this error infrequently (17.7.dev):
It looks like this stops the service advertisement completely.

``` python
Exception in thread zeroconf-Engine:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.4/dist-packages/zeroconf.py", line 1106, in run
    reader.handle_read(socket_)
  File "/usr/local/lib/python3.4/dist-packages/zeroconf.py", line 1164, in handle_read
    self.zc.handle_response(msg)
  File "/usr/local/lib/python3.4/dist-packages/zeroconf.py", line 1937, in handle_response
    self.update_record(now, record)
  File "/usr/local/lib/python3.4/dist-packages/zeroconf.py", line 1918, in update_record
    self.notify_all()
  File "/usr/local/lib/python3.4/dist-packages/zeroconf.py", line 1720, in notify_all
    self.condition.notify_all()
  File "/usr/lib/python3.4/threading.py", line 358, in notify_all
    self.notify(len(self._waiters))
  File "/usr/lib/python3.4/threading.py", line 341, in notify
    waiters_to_notify = _deque(_islice(all_waiters, n))
RuntimeError: deque mutated during iteration
```

**Comment by stephenrauch** [comment]
Ouch...

I love the fact that you are so hard on this code.  Hopefully it will eventually get beaten into shape.

That exception is actually in the threading library.  I don't immediately know how to fix it expect to catch and ignore the exception.  But that may also have some unintended consequences.  I do not see how zeroconf's usage of the condition variable is incorrect, but...  I will spend some looking at this.

Thanks for reporting this.

**Comment by stephenrauch** [comment]
Is this python bug biting you?

http://bugs.python.org/issue22185

What version of 3.4 are you using?

**Comment by stephenrauch** [comment]
Ubuntu 14.04 appears to be using python 3.4.0, so I am pretty sure [issue 22185](http://bugs.python.org/issue22185) is the problem.  I have [checked in a work around](https://github.com/stephenrauch/python-zeroconf/commit/16db9d10dfe4cff97b609464ab24c4e71bd1aa68) in my repo for the python library bug.  Would be great if you could give it a try before I merge it.

**Comment by gbiddison** [comment]
This could be it, my Ubuntu machines are running 3.4.3
I appreciate the feedback, wish I had more time to devote to this library, it's been very helpful for us.

**Comment by gbiddison** [comment]
Doing a more thorough audit of python versions here, we are running several versions on Ubuntu from 3.4.0 to 3.4.3
My strategy here is going to be to patch the python versions then wait & see, but looking at the commit history, this exception probably used to get logged & eaten by the general catch-all exception handler around the Engine.run function.  

I am also seeing a second error from the same block: 

```python
Exception in thread zeroconf-Engine:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstap_inner
    self.run()
  File "/usr/local/lib/python3.4/dist-packages/zeroconf.py", line 1101, in run
    rr, wr, er, select.select(rs, [], [], self.timeout)
InterruptedError: [Errno 4] Interrupted system call
```

If you like, I can open a separate issue since it's a different error,  but it seems related since it's roughly the same code.

**Comment by gbiddison** [comment]
And I am adding the work-around you suggested to my systems now; these race-bugs are pretty intermittent...

**Comment by gbiddison** [comment]
Ok, I believe the InterruptedError is due to our use of signal.SIGALRM somewhere else in the code, so I wouldn't expect that to be reproducible here ...

**Comment by jstasiak** [comment]
I'll close this as Python 3.4 is not supported anymore.
