### ISSUE TITLE
remove_service not working?

### ISSUE THREAD

**Issue by gepd** [jstasiak/python-zeroconf#79]
I'm running the example in the main page:
```
from six.moves import input
from zeroconf import ServiceBrowser, Zeroconf


class MyListener(object):

    def remove_service(self, zeroconf, type, name):
        print("Service %s removed" % (name,))

    def add_service(self, zeroconf, type, name):
        info = zeroconf.get_service_info(type, name)
        print("Service %s added, service info: %s" % (name, info))


zeroconf = Zeroconf()
listener = MyListener()
browser = ServiceBrowser(zeroconf, "_http._tcp.local.", listener)
try:
    input("Press enter to exit...\n\n")
finally:
    zeroconf.close()
```
I don't know really if the `remove_service`  listener is not working or I'm doing something wrong.

I've a 'Nodemcu' device, I'm browsing in `_arduino._tcp.local.` so when I turn on the device I can see all the available information. But when I unplug the device, nothing happens. 

The `Service name removed` text should appears inmediatle or should I wait?

How could I solve this issue?

I'm using Py 2.7

**Comment by stephenrauch** [comment]
Remove service requires the removed service to announce that it is leaving.  Just unplugging the device will not do that.  I believe that eventually the browser, if it has not heard from the device, will timeout the record and the service will be removed, but I believe that timeout is an hour.

**Comment by gepd** [comment]
Thanks @stephenrauch 
I don't know if is the best solution but I've solved calling `add_service` each time I need.
