### ISSUE TITLE
socket error 10022 on windows with multiple ip addresses on an interface

### ISSUE THREAD

**Issue by Desertification** [jstasiak/python-zeroconf#81]
The following sample code throws an exception when running on a windows with multiple ip addresses on one ethernet interface.

![img_26072016_001656](https://cloud.githubusercontent.com/assets/2457184/17119633/63807b58-52c7-11e6-9dc2-2637aa5cbd58.png)
### code

`print('\n'.join(ZeroconfServiceTypes.find()))`
### exception

  File "C:\Python27\lib\site-packages\zeroconf.py", line 1406, in find
    local_zc = zc or Zeroconf()
  File "C:\Python27\lib\site-packages\zeroconf.py", line 1523, in init
    socket.inet_aton(_MDNS_ADDR) + socket.inet_aton(i))
  File "C:\Python27\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 10022] An invalid argument was supplied

The code runs without problems when I remove one of the ip addresses.
I found this bug accidentally and won't have any setups like that normally.
Hope this helps someone who also has this exception.

**Comment by stephenrauch** [comment]
Thanks for reporting this.  Was able to duplicate this, the problem is that one of the addresses is invalid.  We will get a fix posted soon.

**Comment by bdraco** [comment]
@Desertification Is this still reproducible ?

**Comment by bdraco** [comment]
There has been a lot of refactoring here that may have resolved this. Since this has gone stale, I'm going to close it out.  Please reopen if its still reproducible.
