### ISSUE TITLE
Let pip2 know where to find the latest zeroconf for Python2?

### ISSUE THREAD

**Issue by kjcole** [jstasiak/python-zeroconf#89]
Sadly, in spite of claims to the contrary, Python 2 is not yet dead, and I find myself in need of ZeroconfServiceTypes, which hasn't made it into the Python 2 package...

**Comment by stephenrauch** [comment]
2.7? Or something older?

**Comment by kjcole** [comment]
Sorry. 2.7 would be good enough.

**Comment by stephenrauch** [comment]
I use this library in 24x7 production environment with python 2.7. It has flaws, but for my use case it works great.  Is there a specific issue you have run into?

**Comment by kjcole** [comment]
Yep. ZeroconfServiceTypes() See below:

```
$ pip2 list | grep zeroconf
zeroconf (0.17.6)
```

```
$ python2
Python 2.7.12+ (default, Sep 17 2016, 12:08:02) 
[GCC 6.2.0 20160914] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from zeroconf import ZeroconfServiceTypes
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name ZeroconfServiceTypes
```

```
$ pip3 list | grep zeroconf
zeroconf (0.17.6)
```

```
$ python3
Python 3.5.2+ (default, Sep 22 2016, 12:18:14) 
[GCC 6.2.0 20160927] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from zeroconf import ZeroconfServiceTypes
>>> 
```

**Comment by kjcole** [comment]
(Oops. I accidentally clicked [Close and comment] instead of [Comment]. Didn't intend to close the issue.)

**Comment by stephenrauch** [comment]
Maybe there is an install issue?  I am running on windows, but here is what I got (output slightly trimmed):
```
>pip install zeroconf
Collecting zeroconf
  Downloading zeroconf-0.17.6-py2.py3-none-any.whl
Successfully installed zeroconf-0.17.6

>python
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from zeroconf import ZeroconfServiceTypes
>>>
```

You might also try:

```
>>> import zeroconf
>>> print '\n'.join(dir(zeroconf))
AbstractMethodException
BadTypeInNameException
DNSAddress
...
```

**Comment by kjcole** [comment]
Revising the issue: Push the latest to wherever pip2 retrieves stuff. ;-)

cloning this repository and manually issuing "python2 setup.py install" instead of "pip2 install --upgrade zeroconf" worked. However, pip2 continued to fail to do the right thing even after uninstalling zeroconf.

**Comment by stephenrauch** [comment]
I looked up [pip2](https://pypi.python.org/pypi/pip2/0.0.1.dev1) and got this:

_Development Status :: 2 - Pre-Alpha_

So I am unlikely to spend much time researching this, maybe others would.  But pull requests are welcome.

**Comment by Calinou** [comment]
Since Python 2 is now EOL, is this issue still relevant?

**Comment by jstasiak** [comment]
Most likely not.
