### ISSUE TITLE
Sync mode no longer works when asyncio event loop is running

### ISSUE THREAD

**Issue by jacobtomlinson** [jstasiak/python-zeroconf#893]
Thanks for all the hard work here, really excited to see the `asyncio` support released.

However I've noticed a bug that the original threaded mode no longer works if the `asyncio` event loop is running.

```python
import asyncio

from zeroconf import IPVersion, ServiceInfo, Zeroconf


def get_addresses_for_service(service: str):
    with Zeroconf(ip_version=IPVersion.V4Only) as zeroconf:
        service = zeroconf.get_service_info("_http._tcp.local.", service, 3000)
        for addr in service.parsed_addresses():
            print(f"{addr}:{service.port}")


async def run():
    get_addresses_for_service("_mysvc._http._tcp.local.")


if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(run())
```

```python-traceback
Traceback (most recent call last):
  File "/tmp/test.py", line 28, in <module>
    loop.run_until_complete(run())
  File "/Users/jtomlinson/miniconda3/envs/dask/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/tmp/test.py", line 22, in run
    get_addresses_for_service("_sched-7bca6959._dask._tcp.local.")
  File "/tmp/test.py", line 9, in get_addresses_for_service
    service = zeroconf.get_service_info("_dask._tcp.local.", service, 3000)
  File "/Users/jtomlinson/Projects/jstasiak/python-zeroconf/zeroconf/_core.py", line 449, in get_service_info
    if info.request(self, timeout, question_type):
  File "/Users/jtomlinson/Projects/jstasiak/python-zeroconf/zeroconf/_services/info.py", line 427, in request
    raise RuntimeError("Use AsyncServiceInfo.async_request from the event loop")
RuntimeError: Use AsyncServiceInfo.async_request from the event loop
```

Despite creating a regular `Zeroconf` object within a synchronous function I'm getting an exception saying that I need to use async functionality. This works as expected if I downgrade to `0.31.0`.

To work around this I could change the synchronous function to be async and use the new functionality, but this would break the library API for users which I would rather avoid.

OS: `macOS 10.15.7`
Python: `3.8`
Zeroconf: `0.32.0`

**Comment by jacobtomlinson** [comment]
Even simpler test that fails

```python
@pytest.mark.asyncio
async def test_sync_within_event_loop() -> None:
    """Test sync version still works within an event loop."""
    zc = Zeroconf(interfaces=['127.0.0.1'])
    assert zc.get_service_info("_neverused._tcp.local.", "xneverused._neverused._tcp.local.", 10) is None
    zc.close()
```

```python-traceback
FAILED tests/test_asyncio.py::test_sync_within_event_loop - RuntimeError: Use AsyncServiceInfo.async_request from the event loop
```

**Comment by bdraco** [comment]
`get_service_info` is not async safe because it will block your event loop (is will in 0.31.0 as well). The RuntimeError guard is intentional to make sure the async version is called in async context.

**Comment by jacobtomlinson** [comment]
Thanks for the response @bdraco.

I agree that it isn't async safe (and never was), but I am providing both an async and sync API to my users with the understanding that the sync API will be blocking. So this change has broken my project for my users.

I appreciate you are trying to protect folks from bad practice but I think enforcing that the sync version cannot be used within an event loop with a `RuntimeError` is an overstep here.
