### ISSUE TITLE
missing `x` permission on directories on pypi source tar

### ISSUE THREAD

**Issue by dirkmueller** [jstasiak/python-zeroconf#923]
I wasn't able to find the code that generates the tarball that is uploaded to pypi anywhere, but I hope this reaches the right place.. the tar uploaded there is very hard to use as the directory permissions are missing `u+x` permissions:

```
tar tvf zeroconf-0.33.0.tar.gz   |head
drw-rw-rw- root/root         0 2021-07-19 07:07 zeroconf-0.33.0/
```

ideally directories would be 755 or 750

**Comment by bdraco** [comment]
Sorry about that. I have a overly restrictive umask the machine I pushed it from.  I'll push a 0.33.1 with u+x

**Comment by bdraco** [comment]
0.33.1 published

**Comment by bdraco** [comment]
Was this causing problems installing with pip?
