### ISSUE TITLE
allow_name_change parameter seems to have no effect

### ISSUE THREAD

**Issue by animalmutch** [jstasiak/python-zeroconf#927]
Hi. I'm interested in using your library for a project, but I'm not seeing expected behaviour. It's possible I'm misunderstanding the expected behaviour, so please let me know if so. I want to use zeroconf for node discovery in a network with a leader node and many follower nodes. The follower nodes  should advertise their services as followers using zeroconf. The follower nodes can't all be preconfigured with a unique service name, but each should use a 'name pattern', so that the leader node can discover all nodes advertising a particular service type, and communicate with any that are offering a service name that matches a pattern. It was my understanding that the 'allow_name_change' parameter would allow exactly this use case, as it appears that it's supposed to just append a number to the given name to allow services with the same name to be advertised on a network. I can get a ServiceBrowser working that will find services with different names, but when I give two services the same name, and set 'allow_name_change = True', the Service Browser only finds the first service. Am I missing something? Here's some code snippets:

Listener:

```
from zeroconf import Zeroconf, ServiceBrowser, ServiceListener

class Listener(ServiceListener):
    def add_service(self, zc: 'Zeroconf', type_: str, name: str) -> None:
        print("I found a service :)")
    def remove_service(self, zc: 'Zeroconf', type_: str, name: str) -> None:
        print("I lost a service :(")
    def update_service(self, zc: 'Zeroconf', type_: str, name: str) -> None:
        print("A service changed :|")

zc = Zeroconf()
serviceBrowser = ServiceBrowser(zc, "_project._tcp.local.", Listener())
serviceBrowser.run()
```
Service:
```
import time
from zeroconf import ServiceInfo, Zeroconf

zc = Zeroconf()

serviceInfo = ServiceInfo("_project._tcp.local.", "_one._project._tcp.local.", 8081)

zc.register_service(serviceInfo, allow_name_change=True)
startTime = time.time()
while time.time() < startTime + 60:
    time.sleep(1)
zc.unregister_service(serviceInfo)
```

**Comment by bdraco** [comment]
Allow name change will increment the name by adding `-2`, `-3`, ... if a conflicting service is already registered on the network.

**Comment by animalmutch** [comment]
Thanks @bdraco . In this case there is a conflicting service registered: I have two instances of the Service code above running at once on different network nodes, but the Listener instance doesn't see two services with the suffixes '-1' and '-2'. Only if I give the services different names does the listener see more than one service.

**Comment by bdraco** [comment]
Can you send a small bit of code that replicates the issue?

We just started using this codepath in Home Assistant so we are about to get a lot more feedback on it as well (https://github.com/home-assistant/core/pull/53476)

**Comment by animalmutch** [comment]
Hi @bdraco. The above code replicates the issue. I run two instances of the code marked 'Service' and one of the code marked 'Listener' all on different machines connected to a LAN

**Comment by bdraco** [comment]
Try taking the underscore out from `_one` as I don't think thats a valid name.

**Comment by bdraco** [comment]
Please try 0.34.0

**Comment by bdraco** [comment]
Should have been fixed in https://github.com/jstasiak/python-zeroconf/pull/940
