### ISSUE TITLE
not updating services after wifi connectivity change

### ISSUE THREAD

**Issue by AnEx07** [jstasiak/python-zeroconf#976]
not updating services after wifi connectivity change.
if i stop menualy and restart listener it works perfectly is there any event to know if listener fail to get service update.

**Comment by bdraco** [comment]
There isn't support for detecting network changes.  This has to be implemented externally to the library.

**Comment by AnEx07** [comment]
can you suggest how to...

**Comment by bdraco** [comment]
Monitoring system interfaces is outside of the scope of what zeroconf is expected to do.

How this issue the below solved might provide some help in this case:
https://github.com/home-assistant/core/issues/59553
