### ISSUE TITLE
Feature Request: ability to update a registered service

### ISSUE THREAD

**Issue by yann-l** [jstasiak/python-zeroconf#98]
Once a service is registered with zeroconf.register_service(info), I don't find a way to update it. As a example, let's take the registration.py in example folder. I'd like to be able to change the 'path' in the desc variable and update the service that has been registered. Avahi and Bonjour allow that.

I'm  not familiar enough with zeroconf to provide a patch unfortunately.

**Comment by lovetox** [comment]
Yes this would be great to have

**Comment by jstasiak** [comment]
Resolved in https://github.com/jstasiak/python-zeroconf/pull/166, will be a part of the next release.
