### ISSUE TITLE
Allow _ in side of service.

### ISSUE THREAD

**Issue by wgaylord** [jstasiak/python-zeroconf#99]
Many services have a _ inside there service name. The current code does not allow for them to be used.

(Latest pip install for py 2.7)

**Comment by jstasiak** [comment]
Can you provide the full error message you get when this happens?

**Comment by cockroach** [comment]
I'm not the original reporter but I'm also seeing this.

The error is

> zeroconf.BadTypeInNameException: Service name (ibisip_http) must contain only these characters: A-Z, a-z, 0-9, hyphen ('-')

Adding the underscore ("_") to the list of allowed characters in zeroconf.py (_HAS_ONLY_A_TO_Z_NUM_HYPHEN) fixes the issue for me.

**Comment by jstasiak** [comment]
What python-zeroconf version are you using? This should be fixed in 0.21.3. If you're still seeing this on 0.21.3 please provide full stack trace.

**Comment by wgaylord** [comment]
This works in the latest version from what I can tell. I sort of abandoned the project I was going to use this with a while ago which is why I forgot about this issue.
